### ISSUE TITLE
Pets cleanup

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#100]
I pushed an commit today to add pet folders (currently pet image urls are hard coded based on their ID) to offer a more modular way of dealing with those images.

As a result I went through a few of the templates and I've did a bit of editing, but I'm sure a few things broke. 

Tomorow I'm going to do a full sweep of all the code in the pet module to see if I can improve the code's modularity.

**Comment by curtisdelicata** [comment]
I can't look at the code at the moment as not on my laptop. Is it still possible for locked colours and locked species (I think I seen locked species but not locked colours??)

**Comment by happyDemon** [comment]
I think you mean it the other way around? I haven't seen the locked pet species xD I could implement this (e.g. the locked pet species could have a create limit in the adopt, once it reaches 0 they'd disapear)

**Comment by curtisdelicata** [comment]
Yes you are correct. I meant are there still locked colours. Locked species could be useful too.

**Comment by curtisdelicata** [comment]
Locked colours would be used with 'paint brushes'. As long as that works I am happy.

Do not worry about locked species though, we don't need that for 1.0
