### ISSUE TITLE
User preferences

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#106]
Our current way of dealing with user preferences have been to simply throw all options into the user table. It's quite a unreasonable way to deal with it, and we need a better way.

One way to deal with it would be to have a user_preferences table containing key, value data. This might turn out to be quite slow to process as joining 5-20 tables every time we load a user isn't acceptable for performance.

We could cache the information in the user table, with json or serialized php, and update it every time the user preferences for a user changes.

The table design would be something like:

```
user_id int unsigned
key string
value text (or some other data format)
```

Unless anyone have any other ideas I will implement this shortly as it is required for #4.

**Comment by curtisdelicata** [comment]
This sounds good. I cannot think of any other way.

**Comment by Hinton** [comment]
I completed the initial version of user_properties. What's left to do is change everything to use it.

I discussed with @happyDemon how we could deal with avatars and my suggestion is to use a "drivers" system. Each avatar system has it's own class that extends the avatar base class, with a few functions such as `url`, `validate`, `save($data)`.

For example the gravatar class would look something like this:

``` php
class Avatar_Gravatar extends Avatar
{

    public function __construct(Model_User $user, array $data)

    public function url()
    {
        return 'http://www.gravatar.com/avatar/'.md5(strtolower($this->user->email)).'?s=64';
    }

}
```

We should provide a clean wrapper for it in the user model, something along with:

``` php
function avatar()
{
    return Avatar::factory($this, $this->get_property('avatar'));
}
```

The format for the property should be:

``` php
array(
    'driver' => 'gallery',
    'id'     => 1
);
```

**Comment by curtisdelicata** [comment]
Sounds good.

**Comment by curtisdelicata** [comment]
How is this progressing?

**Comment by Hinton** [comment]
We just have to update all existing calls to about, signature and the other fields before we close this.
I decided to finish user settings before, as there isn't any point in updating the old system when we need to do a complete rewrite for the new.

**Comment by curtisdelicata** [comment]
Signature works in forum using the new code but avatar doesn't work (Set it to use gravatar)

**Comment by curtisdelicata** [comment]
It doesn't work even if I use a valid Gravatar email. It shows it ok in user settings.

**Comment by curtisdelicata** [comment]
It works now that I updated the drivers to be case sensitive.

**Comment by curtisdelicata** [comment]
Can this now be closed?

**Comment by Hinton** [comment]
Not yet, we should have a migration that removes old fields from user table, and forum has to be updated (post-count).
