### ISSUE TITLE
Rename modular-gaming directory to modulargaming

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#107]
We should rename the modular-gaming directory to modulargaming, or mg. It's quite bothersome having a space in the directory and it looks out of place compared to all other locations.

**Comment by happyDemon** [comment]
+1

**Comment by Hinton** [comment]
We need to decide if we should go with mg or modulargaming. Modulargaming is quite a bit to type, so mg might be better.

**Comment by curtisdelicata** [comment]
I think modulargaming is best as it is descriptive. mg is not obvious.

**Comment by Lewis** [comment]
I think modulargaming is better. It looks odd with the hyphen.
