### ISSUE TITLE
Better Avatar system

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#108]
Split from #106.

I discussed with @happyDemon how we could deal with avatars and my suggestion is to use a "drivers" system. Each avatar system has it's own class that extends the avatar base class, with a few functions such as `url`, `validate`, `save($data)`.

For example the gravatar class would look something like this:

``` php
class Avatar_Gravatar extends Avatar {

    public function __construct(Model_User $user, array $data)

    public function url()
    {
        return 'http://www.gravatar.com/avatar/'.md5(strtolower($this->user->email)).'?s=64';
    }

}
```

We should provide a clean wrapper for it in the user model, something along with:

``` php
function avatar()
{
    return Avatar::factory($this, $this->get_property('avatar'));
}
```

The format for the property should be:

``` php
array(
    'driver' => 'gallery',
    'id'     => 1
);
```

**Comment by Hinton** [comment]
The avatar system mostly works, what's left is to fix the user settings page.
But it needs to be completely rewritten to be more modular, see #106.

**Comment by curtisdelicata** [comment]
We would need to update everything that references user settings? (Signature and avatar etc for forum?)

**Comment by curtisdelicata** [comment]
Should avatar be in core or user module? I guess core (Where you put it) makes sense, up to you.

**Comment by Hinton** [comment]
Hmm, I wonder if we should close this, the only thing left is the user settings page.

**Comment by curtisdelicata** [comment]
We need to make sure forum supports the new avatar as well as user profile obviously.

**Comment by Hinton** [comment]
The forum should already support them, user profile is currently being redone.

**Comment by curtisdelicata** [comment]
I forgot that we weren't changing the avatar_id field. Forum should work without changes.

**Comment by Hinton** [comment]
Well, all avatars fields from the user should be removed. We should use the new avatar() function to retrieve the avatar data.

**Comment by curtisdelicata** [comment]
Feel free to do so. Thanks.

**Comment by Hinton** [comment]
Most of the avatar system is done, what's left is custom avatar (uploaded).
You can now set enabled avatars from config.

**Comment by curtisdelicata** [comment]
Signature works but avatar doesn't display on forum.

**Comment by curtisdelicata** [comment]
Works now after I renamed driver to be case sensitive.

**Comment by curtisdelicata** [comment]
Can this now be closed? Or is it waiting for custom avatar upload?

**Comment by Hinton** [comment]
Waiting for avatar upload, it should be quite simple to do.
