### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#110]
I talked about this with Oscar last night.

After the release we might want to have a central place where we can offer our own MG modules, making it easier for users to update (e.g. by running php composer.phar update).

We could open this up for third-party developers there's 1 place where people can install MG modules from.

We would need to set up a packagist isntallation on modular gaming.com : http://getcomposer.org/doc/05-repositories.md#packagist
https://github.com/composer/packagist

And create our own installer:
http://getcomposer.org/doc/articles/custom-installers.md
Here's an example: https://github.com/composer/installers/blob/master/src/Composer/Installers/KohanaInstaller.php

**Comment by curtisdelicata** [comment]
This is a good idea. It will have to wait until 1.1.0 as it is not urgent.

**Comment by curtisdelicata** [comment]
Should we use our own installer and custom package system? I think it is better to use normal packagist which would rely on Git submodules?

**Comment by Hinton** [comment]
Using a custom installer with packagist sounds like the easiest solution.

**Comment by curtisdelicata** [comment]
We need to split up packages in modulargaming/ to separate githubs and create Composer packages. Later on we should support installing and updating via admin.

It might be a good idea to package up all modules in /modules and /system too.
