### ISSUE TITLE
Pet Admin - Assigning colours

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#112]
Database_Exception [ 1048 ]: Column 'pet_specie_id' cannot be null [ INSERT INTO `pet_species_colours` (`pet_specie_id`, `colour_id`) VALUES (NULL, '7') ]

**Comment by curtisdelicata** [comment]
I renamed pet_specie_id to specie_id so it matches with using colour_id

I thought it would fix this but it did not. I checked that the form submits it but it doesn't work.

**Comment by curtisdelicata** [comment]
Database_Exception [ 1048 ]: Column 'specie_id' cannot be null [ INSERT INTO `pet_species_colours` (`specie_id`, `colour_id`) VALUES (NULL, '1') ]

**Comment by happyDemon** [comment]
should be fixed, seemed like list.js used an underscore instead of - when adding the pet specie id value to the hidden field
