### ISSUE TITLE
Pet Admin - Colours

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#114]
DataTables warning (table id = 'data-table'): Requested unknown parameter '0' from the data source for row 1

**Comment by curtisdelicata** [comment]
Deleting causes an error too:

Kohana_HTTP_Exception [ 404 ]: The requested URL admin/pet/colour/remove was not found on this server.

Is it supposed to be admin/pet/colour/delete  ?

**Comment by curtisdelicata** [comment]
DataTables warning (table id = 'data-table'): Requested unknown parameter '0' from the data source for row 1

For editing specie too.

**Comment by curtisdelicata** [comment]
It appears to save ok though.

**Comment by happyDemon** [comment]
it's supposed to be remove, the init.php file was using an old standard, should be fixed now

**Comment by happyDemon** [comment]
I'll still have to check if it's been fixed (didn't think about fixing the edit bug), was a little sleep deprived o.O
I'll try to get this done tomorow ^^
