### ISSUE TITLE
Item Admin - Gifting Item

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#116]
It successfully gifts an item but has an error about log:

Database_Exception [ 1241 ]: Operand should contain 1 column(s) [ INSERT INTO `logs` (`user_id`, `location`, `alias`, `agent`, `ip`, `type`, `message`, `params`, `time`) VALUES ('1', 'admin/item/gift', 'item.in.admin.root', ('Chrome', 'Linux'), '127.0.0.1', 'item', 'Player recieved :amount :item_name @ :origin', '{\":amount\":\"1\",\":item_name\":\"1 Malta\",\":origin\":\"admin root\"}', 1362147156) ]

Is it being changed to use the Core log/notify?

**Comment by curtisdelicata** [comment]
I still get a similar error:

Database_Exception [ 1241 ]: Operand should contain 1 column(s) [ INSERT INTO `logs` (`user_id`, `location`, `alias`, `agent`, `ip`, `type`, `message`, `params`, `time`) VALUES ('1', 'admin/item/gift', 'item.in.admin.root', ('Chrome', 'Linux'), '127.0.0.1', 'item', 'Player recieved :amount :item_name @ :origin', '{\":amount\":\"1\",\":item_name\":\"1 Malta\",\":origin\":\"admin root\"}', 1362331733) ]

**Comment by curtisdelicata** [comment]
I fixed it.

$log = $item->to_user($user, 'admin.' <bold>.<bold>  $this->user->username, $this->request->post('amount'));

$log = $item->to_user($user, 'admin.' <bold>,</bold>  $this->user->username, $this->request->post('amount'));

Now I get this error:

ErrorException [ Fatal Error ]: Call to undefined method Item_Exception::errors()
DOCROOT/modulargaming/item/classes/Controller/Admin/Item.php [ 357 ]

**Comment by curtisdelicata** [comment]
If it is calling Item_Exception:errors does that mean it is failing to log now?

**Comment by curtisdelicata** [comment]
I have reverted the change. I now get the same error as before:

Database_Exception [ 1241 ]: Operand should contain 1 column(s) [ INSERT INTO `logs` (`user_id`, `location`, `alias`, `agent`, `ip`, `type`, `message`, `params`, `time`) VALUES ('1', 'admin/item/gift', 'item.in.admin.root', ('Chrome', 'Linux'), '127.0.0.1', 'item', 'Player recieved :amount :item_name @ :origin', '{\":amount\":\"1\",\":item_name\":\"1 Test\",\":origin\":\"admin root\"}', 1362419487)

**Comment by curtisdelicata** [comment]
Is it missing params?

Also shouldn't it say the amount and item name and not :amount and :item_name?

**Comment by happyDemon** [comment]
nope, it's being run through Kohana's __() function which parses the string (http://kohanaframework.org/3.3/guide-api/I18n)

**Comment by curtisdelicata** [comment]
Gifting an item from Inventory just outputs '[object Object]'. It also only auto completes once I typed the four letters.

**Comment by happyDemon** [comment]
if it's for the username then that's normal that it only starts at 4 chars, that's the min_length in the model, would load too much data otherwise.

I'm not getting the [object, Object] error though

**Comment by curtisdelicata** [comment]
It gift the item successfully but it outputs  '[object Object]'

**Comment by happyDemon** [comment]
in the notification box?

**Comment by curtisdelicata** [comment]
Yes.

**Comment by curtisdelicata** [comment]
Gifting item from admin now works fully. Gifting an item from user inventory errors and displays object:

Kohana_HTTP_Exception [ 404 ]: The requested URL inventory/search was not found on this server.

**Comment by curtisdelicata** [comment]
No error but it doesn't gift the item.
