### ISSUE TITLE
item Admin - Creating an item, image

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#118]
When creating an item it doesn't seem to display the image. I believe the image is uploaded though.

**Comment by curtisdelicata** [comment]
It tries to display: http://localhost/assets/img/items/foods/tmp

**Comment by curtisdelicata** [comment]
I have assets/img/items/5 but that is empty. Creating a new item did not create a directory/image

**Comment by curtisdelicata** [comment]
Creating an item with a 80x80 image works.

Creating an item with the wrong size gets stuck on processing and does not error.

**Comment by happyDemon** [comment]
This should be fixed with 8e2f018c661af6656fe84b2ddfd8e9d372d7a432 and 260e51d2dc74047c59c81ddd8427f0877ec8f253

**Comment by curtisdelicata** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/admin/templates.js
Failed to load resource: the server responded with a status of 403 (Forbidden) http://localhost/assets/img/items/foods/tmp/
Uncaught TypeError: Cannot call method 'join' of undefined admin.js:288

**Comment by curtisdelicata** [comment]
That is what I get when I try an image with the wrong size.
