### ISSUE TITLE
Pet - Locked-down colours available only via a paintbrush

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#12]
Firstly to be able to change the colour of a pet. Secondly to be only be able to do so with an item.

**Comment by curtisdelicata** [comment]
We have a special colour 'outline' (id 7)  that should be able to be changed by using a paint brush type admin

**Comment by happyDemon** [comment]
That's easy to add in the item admin. We do, however still need a way to check which specie supports which color before it could be implemented.

**Comment by curtisdelicata** [comment]
At the moment every specie has access to every colour. This may be improved and changed at a later date.
