### ISSUE TITLE
Item Admin - Paginate

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#120]
Paginate error:

Database_Exception [ 1052 ]: Column 'id' in where clause is ambiguous [ SELECT `type`.`id` AS `type:id`, `type`.`name` AS `type:name`, `type`.`action` AS `type:action`, `type`.`default_command` AS `type:default_command`, `type`.`img_dir` AS `type:img_dir`, `item`.`id` AS `id`, `item`.`type_id` AS `type_id`, `item`.`name` AS `name`, `item`.`description` AS `description`, `item`.`image` AS `image`, `item`.`status` AS `status`, `item`.`unique` AS `unique`, `item`.`transferable` AS `transferable`, `item`.`commands` AS `commands` FROM `items` AS `item` LEFT JOIN `item_types` AS `type` ON (`type`.`id` = `item`.`type_id`) WHERE (`id` LIKE '%t%' OR `name` LIKE '%t%' OR `image` LIKE '%t%' OR `status` LIKE '%t%' OR `type` LIKE '%t%') ORDER BY `id` ASC LIMIT 10 OFFSET 0 ]

3:49 PM
http://localhost/admin/item/paginate?sEcho=11&iColumns=5&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&sSearch=t&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&iSortCol_0=0&sSortDir_0=asc&iSortingCols=1&bSortable_0=false&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=false&_=1362497864879
3:49 PM
Paginate search works on types etc but not items
3:49 PM
It doesn't work on recipes though
3:50 PM
It gets stuck on processing

**Comment by happyDemon** [comment]
The paginate module does not handle relations, nor is this necesary, I'll create a seperate way to do this, but isn't important at the moment.

**Comment by curtisdelicata** [comment]
ErrorException [ Recoverable Error ]: Argument 1 passed to Kohana_Paginate::search_columns() must be of the type array, string given, called in /var/www/modulargaming/item/classes/Controller/Admin/Item.php on line 153 and defined
6:54 PM
ErrorException [ Recoverable Error ]: Argument 1 passed to Kohana_Paginate::search_columns() must be of the type array, string given, called in /var/www/modulargaming/item/classes/Controller/Admin/Item/Recipes.php on line 42 and defined

**Comment by curtisdelicata** [comment]
I fixed it by placing it in an array.
