### ISSUE TITLE
item Admin - Creating an item, auto complete

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#121]
It doesn't auto complete commands for recipe, paint and transform.

**Comment by happyDemon** [comment]
how do you mean, does it give an error in the console? or isn't it sending the request, because by checking the code it should be working

**Comment by curtisdelicata** [comment]
No errors.

I mean when you are defining which pet the item should transform into it does not auto complete the pet name. Same for recipe and paint.

**Comment by curtisdelicata** [comment]
Console says "No Properties"

**Comment by curtisdelicata** [comment]
0: "Black"

It worked once but it didn't work again.
