### ISSUE TITLE
Inventory - Feeding and play doesn't show up

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#124]
Not sure when this changed but I tested now and it doesn't let you feed or play with a pet anymore.

**Comment by curtisdelicata** [comment]
The links do not appear.

**Comment by happyDemon** [comment]
This only happens when you don't have any pets (since the action wouldn't be of any use then). Shows up when you have a pet.

**Comment by curtisdelicata** [comment]
My mistake, I should of noticed that! It appears now but does not seem to work. I have tested when hunger is not 100.

I get an error about log too:

ErrorException [ Warning ]: Illegal string offset 'username'
DOCROOT/modulargaming/core/classes/Journal.php [ 71 ]
