### ISSUE TITLE
Inventory - Gifting

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#125]
ErrorException [ Warning ]: Illegal string offset 'title'
DOCROOT/modulargaming/core/classes/Journal.php [ 76 ]

I still see [object Object] too.

**Comment by curtisdelicata** [comment]
It does gift successfully but does not log/notify (I tried to use Journal::notify and that has error too)

**Comment by curtisdelicata** [comment]
ErrorException [ Strict ]: Non-static method Journal::notify() should not be called statically, assuming $this from incompatible context

**Comment by curtisdelicata** [comment]
It seems to have two notifies, one in transfer and one on the gift function. I deleted the transfer one and I get a different error:

ErrorException [ Fatal Error ]: Call to a member function notify() on a non-object
DOCROOT/modulargaming/item/classes/Controller/Item/Inventory.php [ 349 ]

**Comment by curtisdelicata** [comment]
Actually are both required?

**Comment by curtisdelicata** [comment]
Back to error:

ErrorException [ Strict ]: Non-static method Journal::notify() should not be called statically, assuming $this from incompatible context

DOCROOT/modulargaming/item/classes/Model/User/Item.php [ 102 ]

**Comment by curtisdelicata** [comment]
If I change it to static I get a different error but setting it as static breaks item admin gift.

**Comment by curtisdelicata** [comment]
I was trying a lot of different thing to try and get it working. Sorry if I did anything wrong with it. @happyDemon

**Comment by happyDemon** [comment]
most of the changes you made should be reverted as they break how the api was designed to be used :s

**Comment by curtisdelicata** [comment]
I now get same error as before:

ErrorException [ Warning ]: Illegal string offset 'title'

**Comment by curtisdelicata** [comment]
Works now.
