### ISSUE TITLE
Item Admin - Creating item, image upload

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#126]
Should item admin use the same image method as avatar upload?

```
                    // Save the image.
                    Image::factory($file)
                            ->resize($this->width(), $this->height())
                            ->save($directory.$this->_filename());

                    // Delete the temporary file
                    unlink($file);
```

**Comment by happyDemon** [comment]
This might be easier indeed, I'll start implementing ^^

**Comment by happyDemon** [comment]
Pet admin's up next, will be for tomorow

**Comment by curtisdelicata** [comment]
Thank you! Item creation works when you use 80x80 if you use any other size it fails though. Shouldn't it resize?

**Comment by happyDemon** [comment]
nope, the owner of the game should set the exact sizes in the config file, no resizing should occur.
I do hope it's returns an error in the UI when it's not the right size

**Comment by curtisdelicata** [comment]
It doesn't return an error.

**Comment by curtisdelicata** [comment]
In error console I get:

Kohana_HTTP_Exception [ 403 ]: CSRF check failed!

**Comment by curtisdelicata** [comment]
I took a look and could not find anything. CSRF seems to be set in index.mustache
