### ISSUE TITLE
Pet Admin - Editing pet specie

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#127]
DataTables warning (table id = 'crud-container'): Requested unknown parameter '0' from the data source for row 0

**Comment by curtisdelicata** [comment]
It updates successfully though.

**Comment by curtisdelicata** [comment]
Same happens with pet colours.

This happens on both Firefox and Chromium on Ubuntu 12.10

**Comment by happyDemon** [comment]
must be a problem with parsing the JSON on the server side, I'll get to it ^^

**Comment by curtisdelicata** [comment]
Any luck?
