### ISSUE TITLE
Admin - templates.js missing

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#128]
I get an error that templates.js is missing.

**Comment by curtisdelicata** [comment]
Is templates.js required as nothing seems to break?

**Comment by curtisdelicata** [comment]
@hinton said it meant to be a Controller. Nothing seems to break though. Is this required for 1.1 or a later release?

**Comment by Hinton** [comment]
I do not think we use this file any longer, so we can probably remove it.

**Comment by Hinton** [comment]
We don't have the error any longer, templates.js was a legacy from my original admin system and in my opinion a cleaner way to handle the templates than the current.
