### ISSUE TITLE
Preview release

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#129]
As per @Hinton idea on Hall.

Should we migrate hinton/mg to modulargaming/modulargaming before we release 1.0 as it will hopefully interest people and will help us find any bugs.

**Comment by curtisdelicata** [comment]
@Lewis
@HappyDemon

**Comment by curtisdelicata** [comment]
When we are ready for preview release I think we should post on the following forums:

http://forum.kohanaframework.org/
http://kohana-modules.com/
http://www.virtualpetlist.com
http://community.bbgamezone.net/projects/
http://indie-resource.com/forums/portal.php
http://www.makewebgames.com/forumdisplay.php/284-Other-Game-engines
http://www.ohloh.net
http://www.pbbgdev.com
http://www.gamedev.net/index
https://forums.digitalpoint.com/forums/php.37/
http://www.sitepoint.com/forums/forumdisplay.php?34-PHP
http://www.sourceforge.net/people/
http://forums.devshed.com/php-development-5/
http://www.devnetwork.net/
http://board.phpbuilder.com/
http://www.phpexpertsforum.com/others-f86.html
http://www.webdeveloper.com/forum/
http://www.codingforums.com/
http://forums.phpfreaks.com/
http://www.theadminzone.com/forums/
http://forums.somethingawful.com/forumdisplay.php?forumid=44
http://forums.indiegamer.com/
http://www.neogaf.com/forum/forumdisplay.php?f=2
http://www.zealotgaming.com/forum/forum.php
http://www.tgforums.co.uk/forum/
http://uk.gamespot.com/forums/index.html
http://forums.digitalspy.co.uk/forumdisplay.php?f=5
http://www.gaming-forum.org/
http://www.pwnem.com/
http://php.resourceindex.com/detail/

This is a draft of what we should post, links will be added if supported by the forum we are posting on:

We are in the process of creating a open source persistent browser based web game (PBBG) framework which will have all the features to get you started and let you start developing your unique features without having to write all the basics. We have taken a modular approach, you can use only the modules you want. If you wanted just a forum you could enable only the core, user and forum modules.

We are building our framework using Kohana which is an open source, object oriented (H)MVC web framework built using PHP5 by a team of volunteers that aims to be swift, secure, and small. We are using Kohana 3.3 with many modules, including the following:

1.) ORM is a a powerful Object Relational Mapping (ORM) module that uses the active record pattern and database introspection to determine a model's column information. 
2.) Mustache is a template specification we use for our templates, we use Kostache's implementation.

You can download our preview release at https://sourceforge.net/projects/modulargaming/files/ You can view a demo at http://demo.modulargaming.com If you have any questions, bugs or feature requests feel free to post them on the issue tracker at GitHub. https://www.github.com/modulargaming/modulargaming

Licensed under a BSD license. Modular Gaming can be used legally for any open source, commercial, or personal project.

Regards,

Modular Gaming
http://www.modulargaming.com

**Comment by happyDemon** [comment]
thumbs up for this :D

**Comment by Hinton** [comment]
We should post on virtualpetlist, and http://forum.pbbghub.com/ seems to be a private forum for 4 games, so perhaps we should not post there.

**Comment by curtisdelicata** [comment]
Your are right, I just noticed they are a private forum. I was just 
about to add virtualpetlist

**Comment by curtisdelicata** [comment]
I am happy with the draft now. I welcome any modifications. What do you all think?

@hinton @happyDemon  @Lewis @jannesiera

**Comment by Lewis** [comment]
Looks good.

**Comment by curtisdelicata** [comment]
I have created a new milestone for preview release.

**Comment by curtisdelicata** [comment]
http://forum.kohanaframework.org/discussion/11680/modular-gaming-open-source-browser-based-game-framework-kohana-3-3
http://www.virtualpetlist.com/showthread.php/15953-Modular-Gaming-Open-source-pet-web-game-framework?p=163494#post163494
http://community.bbgamezone.net/projects/modular-gaming-open-source-web-game-framework-kohana-3-3/new/#new
http://indie-resource.com/forums/viewtopic.php?f=65&t=6657
http://www.pbbgdev.com/forum/forum_posts.asp?TID=527&PID=2455#2455

**Comment by curtisdelicata** [comment]
http://www.gamedev.net/topic/641450-modular-gaming-open-source-browser-based-game-framework/
https://forums.digitalpoint.com/threads/modular-gaming-open-source-browser-game-framework.2649093/
http://www.sitepoint.com/forums/showthread.php?1023931-Modular-Gaming-Open-source-web-game-framework&p=5384136#post5384136
http://www.devnetwork.net/viewtopic.php?f=72&t=137647&sid=2b0509f1bda90862d4fdcd1a6b4437cf
http://board.phpbuilder.com/forumdisplay.php?10-Coding

**Comment by curtisdelicata** [comment]
http://www.codingforums.com/forumdisplay.php?f=6
http://forums.devshed.com/php-development-5/modular-gaming--open-source-web-game-framework-943112.html#post2869066

**Comment by curtisdelicata** [comment]
http://www.makewebgames.com/showthread.php/43210-Modular-Gaming-Open-source-web-game-framework-Kohana-3-3?p=288713#post288713
