### ISSUE TITLE
Pet - Hunger/happiness levels

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#13]
A pet should have hunger and happiness levels which gradually go down and are restored using items.

What should we use for lowering the hunger and/or happiness levels? Minion task?

**Comment by Hinton** [comment]
We should avoid using cron, it might be better to call a function whenever the pet is loaded that calculate how much the hunger/happiness level should lower (depending on last update time).

**Comment by curtisdelicata** [comment]
We should use timestamps to check for updates?

Would we still use Cron or Minion  for site maintenance tasks?

**Comment by Hinton** [comment]
Cron that calls minion sounds like a good idea.

Minion is command line interface to kohana, while cron is a time based job, 2 different things.

**Comment by curtisdelicata** [comment]
and**

I meant to say Cron and Minion.

**Comment by curtisdelicata** [comment]
Should we use a minion task called by cron?
