### ISSUE TITLE
Points property

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#130]
Points needs to be updated to use set/get_property.

**Comment by curtisdelicata** [comment]
I can't find where get_property is in forum?

**Comment by curtisdelicata** [comment]
I found it in message:

'avatar' => $this->message->sender->avatar(),
'signature' => $this->message->sender->get_property('signature'),

**Comment by Hinton** [comment]
View classes?

**Comment by curtisdelicata** [comment]
I found it now, not sure how I missed it!
