### ISSUE TITLE
Public forum

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#135]
I was talking about a public forum and @hinton mentioned that we should use our own code and not other software such as PhpBB.

I changed protected to FALSE and now I get this error.

ErrorException [ Fatal Error ]: Call to a member function can() on a non-object

DOCROOT/modulargaming/forum/classes/View/Forum/Category/View.php [ 67 ]

62  }
63 
64  public function can_create()
65  {
66 
67      return Auth::instance()->get_user()->can('Forum_Topic_Create', array('category' => $this->category));
68  }
69

**Comment by Hinton** [comment]
get_user returns null if user is not logged in. It's documented in the api docs.

**Comment by curtisdelicata** [comment]
```
            if (Auth::instance()->get_user() == NULL)
            {
            return FALSE;
            }

            else
            {
                    return Auth::instance()->get_user()->can('Forum_Poll_Create', array('topic' => $this->topic));
            }
```

This works, but I assume isn't the best way of doing it.

**Comment by Hinton** [comment]
Perhaps this can be closed now?

We should consider redesigning the forum system, it looks quite bad design wise, perhaps @Lewis got any good ideas for the design?

I improved the topic list slightly but there are plenty of things to improve.

**Comment by curtisdelicata** [comment]
I agree that we should remove custom delete code and use constraints instead. Do you have any ideas @Lewis @happyDemon @jannesiera

**Comment by curtisdelicata** [comment]
This works as expected. Closed.
