### ISSUE TITLE
Shop log fails

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#137]
ErrorException [ Notice ]: Trying to get property of non-object

DOCROOT/modulargaming/item/classes/Controller/Item/Shop.php [ 254 ]

249         }
250 
251         $this->view = new View_Item_Shop_Logs;
252 
253         $logs = ORM::factory('Log')
254             ->where('alias', '=', 'user_shop.' . $shop->id)

**Comment by happyDemon** [comment]
This is very strange o.O will check it out tomorow
