### ISSUE TITLE
Forum create topic

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#141]
You can create a forum topic even if content is empty.
It will create a topic but not a post for it.
We should load both validation objects in the controller and validate them before creating.

It would also be a good idea to move the first post creation to topic model.

**Comment by curtisdelicata** [comment]
I agree. Not sure about first post though, up to you.

**Comment by curtisdelicata** [comment]
Can this be closed now?

**Comment by Hinton** [comment]
Yes
