### ISSUE TITLE
Forum - Replies

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#149]
Views count but replies are not counted.

**Comment by curtisdelicata** [comment]
Views went up to 3 but doesn't seem to add any views after this.

**Comment by Hinton** [comment]
Check the code? It only increases views if it's not a "repetitive" view. You have to visit another topic before re-visiting to increase again. Not sure if its a good feature or not, but it prevents view count from increasing while navigating the topic pages.

**Comment by curtisdelicata** [comment]
Strange how it got to 3 as I only viewed it as one user, maybe it was 
using the old code when it added up. Replies are not counted though.

**Comment by curtisdelicata** [comment]
I tested again and views don't go past one per user. Replies does not 
work though.

**Comment by Lewis** [comment]
Replies are counted. Can this be closed?

**Comment by Hinton** [comment]
@Lewis I think so, I believe I never closed the issue due to lack of full testing.

**Comment by curtisdelicata** [comment]
Works as expected.
