### ISSUE TITLE
Assets refactor

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#168]

**Comment by Hinton** [comment]
Started the refactor in branch feature/assets-refactor. Thinking about changing the module a bit to better fit our needs.

**Comment by curtisdelicata** [comment]
Ok great. Should I close old asset issue?

**Comment by Hinton** [comment]
This could be considered closed for now. The new assets system has been implemented in the feature/assets-refactor branch and merged into develop branch.
