### ISSUE TITLE
Seperate directory for assets and uploaded content.

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#170]
Along with the asset refactor we should seperate the assets and upload directories.

The assets directory should contain cached resources, such as images from modules, themes, that should be removed when updating modules.

While Upload contains uploaded items such as user avatars, pets images and should never be removed.

**Comment by curtisdelicata** [comment]
What about assets/cache and assets/upload

**Comment by Hinton** [comment]
Could work, but that would force us to write urls with /cached/ for all images. Images are also cached.

**Comment by Hinton** [comment]
So images would be /assets/cached/img/[file].png

**Comment by curtisdelicata** [comment]
Where would the pet images and item images go? In the actual module/assets?

**Comment by Hinton** [comment]
Pet images would go to upload?

**Comment by curtisdelicata** [comment]
What about the included pet images? I think they should all go in upload

**Comment by Hinton** [comment]
Yea they would should go in upload. Otherwise we have 2 different cases, game specific assets and module provided. Much better to just have 1 case.

**Comment by curtisdelicata** [comment]
What about assets/ and media/

**Comment by curtisdelicata** [comment]
I have moved all images for item, npc, pet to /media

I have also updated all references (img() function in model etc)

@hinton moved glyphs from assets/ to core/assets
