### ISSUE TITLE
Transparent extending

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#173]
Before 1.0 release we should create transparent extending classes for each class, (Boring task). So you can easily override functions in classes.

Should we use the folder MG/ for our classes? Controller_Welcome would be MG_Controller_Welcome.

http://kohanaframework.org/3.3/guide/kohana/extension
- [x] Admin
- [x] Core
- [x] Forum
- [x] Game
- [x] Item
- [x] Message
- [x] Pet
- [x] User

**Comment by curtisdelicata** [comment]
I don't think we should do this as it complicates things.

**Comment by curtisdelicata** [comment]
What do you think? @Lewis @happyDemon @jannesiera

**Comment by Hinton** [comment]
How does it complicate things? Is there another way you can make it easy to extend classes without having to copy and paste the original?

**Comment by curtisdelicata** [comment]
I don't understand? Do you mean you can overwrite specific functions etc using a transparent class? Rather than having to copy all the functions etc you want?

**Comment by Hinton** [comment]
Yea, all Kohanas classes (and modules) provide "empty" classes, that you overwrite (using cascadic file system) to modify and overwrite functions you wish to change. Rather than copying the class and modifying it.

**Comment by curtisdelicata** [comment]
Can you link me an example?

I know that they use empty classes but I didn't realise you could overwrite only specific functions? Can't this be done by the user by overwriting it using application/

**Comment by curtisdelicata** [comment]
Oh I think I understand now? You extend the transparent instead? But how does that copy across all the function?

**Comment by Hinton** [comment]
We overwrite before in controller, https://github.com/modulargaming/modulargaming/blob/develop/modulargaming/core/classes/Controller.php.

**Comment by curtisdelicata** [comment]
Is this needed though? I do think it complicates things?

If you think it is a good idea I guess we should do it though?

Would everything get prefixed? Abstract as well?

**Comment by Hinton** [comment]
It is needed if a user wish to change how a class works. There are plenty of use cases, for example if the user wishes to change how assets are cached, they can overwrite the generate cached assets function rather than copying the whole class. Or if the user wishes to run a query on every page they could add it in controller_frontend rather than copying the whole class and inserting the code.

It's one of the benefits cascadic file system gives, and I see no reason we should not use it.

**Comment by curtisdelicata** [comment]
You are correct.

I think we should use it then.

**Comment by curtisdelicata** [comment]
If you make a start on it so I know how to structure it. I can help later today.

**Comment by curtisdelicata** [comment]
For example if we had a function called x in MG_Controller_Example if you created a function called x in Controller_Example would it overwrite? I assume it does?

**Comment by curtisdelicata** [comment]
If you make a start on it so I know how to structure it. I can help later today.

**Comment by Lewis** [comment]
Good idea.
