### ISSUE TITLE
Last post - Forum

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#177]
Forum category lists the last posted as the original topic starter. Posting replies does not change the last posted user.

**Comment by Hinton** [comment]
I suspect we do not update last_forum_post_id in the reply function, it might be my fault as I migrated over much of the code to the models to clean up the controllers. Should be an easy fix inside the topics model?

**Comment by curtisdelicata** [comment]
I can see it should update on reply. This is from topic model.       

$this->last_post_id = $post->id;
$this->replies++;
$this->save();
