### ISSUE TITLE
Event notification

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#18]
For event notification we currently use Hint. Should we also look into keeping an event log? Or should we leave it as it is.

**Comment by Hinton** [comment]
We should split out parts, form errors can (should?) be done by a regular array that we display close to the inputs.
Hint should be used for notifications that should be displayed on the next page load, perfect for use after redirecting the user (login, logout, post message).

I presume with event notification you are refering to things such as your pet was attacked while you were offline or someone bought an item from your shop.

So we should create a new class for event notification and store events in the database.

**Comment by curtisdelicata** [comment]
I agree with you.
