### ISSUE TITLE
Private Messaging with multiple recipients for a message

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#19]
Messaging needs to be completed.

Regarding multiple recipients, would it make sense to wait and use a form of private forum for this to work? Or should we duplicate messages to each receiver id? I believe the better way would be to have a form of private forum?

**Comment by Hinton** [comment]
We can leave this topic for later, the easiest solution would be to re-use parts of the form system and have topics you can invite persons to, not sure how much code we can share, and if we can use the same database tables.

It should be possible to use the same database tables, if we have a table "messages" with [id, owner, topic_id] and using has_many through.

**Comment by curtisdelicata** [comment]
We will leave this for now until we have forum system working.

**Comment by curtisdelicata** [comment]
Closed for now.
