### ISSUE TITLE
Timezone - add missing timezones

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#20]
To add all the missing timezones to the SQL.

http://en.wikipedia.org/wiki/List_of_time_zones_by_UTC_offset

**Comment by Hinton** [comment]
We should try and keep the amount of timezones down, else we get a crazy large dropdown list, I found a nice array of timezones, http://stackoverflow.com/questions/4755704/php-timezone-list . Should be enought?

**Comment by curtisdelicata** [comment]
I was not going to include them all. I was going to do one for each time. http://stackoverflow.com/questions/4755704/php-timezone-list is a better list, thanks I will add them tomorrow.

**Comment by curtisdelicata** [comment]
I have added the complete list. Closes #20
