### ISSUE TITLE
Login information incorrect..

### ISSUE THREAD

**Issue by OnThePull** [modulargaming/modulargaming#206]
After a user has registered and logs out again, attempting to log in again with the correct username and password gives the error; Login information incorrect! Any ideas?

**Comment by OnThePull** [comment]
Now started again.

**Comment by OnThePull** [comment]
It only seems to affect admin accounts...

**Comment by curtisdelicata** [comment]
I have not experienced this before and cannot reproduce. Can you provide us with more information? What version? Operating System? PHP version?

**Comment by curtisdelicata** [comment]
Have you modified anything in user_roles table? Have you removed role id 1? 1 is login and 2 is admin. You need both.

**Comment by OnThePull** [comment]
User roles have not been changed, PHP version is 5.3, Windows 8 and my Linux VPS, affects both. Newest version of Modular Gaming.

**Comment by curtisdelicata** [comment]
1.0.2 or git/composer?

**Comment by OnThePull** [comment]
1.0.2

**Comment by curtisdelicata** [comment]
What uusername are you using? Any special characters?

**Comment by OnThePull** [comment]
Just admin.

**Comment by curtisdelicata** [comment]
Does 1.0 work?

**Comment by OnThePull** [comment]
I'll try.

**Comment by OnThePull** [comment]
Wrong button.

**Comment by curtisdelicata** [comment]
Thanks. We will test and see if we can confirm. If we can find the issue we will fix asap

**Comment by curtisdelicata** [comment]
I downloaded latest Modular Gaming and tested by creating a user admin with password as password. Logged out and logged back in successfully.

Did you use the drop down or did you manually go to user/logout?

**Comment by Hinton** [comment]
@lpull20 could you post the user and roles_users and role tables? (sql dump). Feel free to obfuscate the passwords.

**Comment by curtisdelicata** [comment]
Both logouts seem to work. I can login on both.

**Comment by curtisdelicata** [comment]
I mentioned user and roles_users before but @ipull20 said he did not change anything.

**Comment by OnThePull** [comment]
I used dropdown, I will post the tables anyway so you can have a look. Give me a sec.

**Comment by OnThePull** [comment]
http://pastebin.com/MXFK2Y6V - roles_users
http://pastebin.com/afcXSL6e - users

**Comment by curtisdelicata** [comment]
Case sensitive is not the problem as I can login with admin or Admin on my local install.

**Comment by OnThePull** [comment]
It's weird how it only affects users given the admin role.

**Comment by curtisdelicata** [comment]
roles_users looks correct.

**Comment by Hinton** [comment]
@lpull20 You have 2 users with the role login, and no admin?

**Comment by Hinton** [comment]
In case you want user with id 1 to be admin, it should be

``` sql
INSERT INTO `roles_users` (`user_id`, `role_id`) VALUES
(1, 1),
(1, 2);
```

**Comment by OnThePull** [comment]
I changed it back to see if it only affected admin accounts, I was admin originally.

**Comment by curtisdelicata** [comment]
What MySQL version are you using?

**Comment by Hinton** [comment]
Just need to be sure, the admin user has BOTH the login and admin role? Login role is required for logging in, without it you won't be able to login.

**Comment by OnThePull** [comment]
Not sure what I did, but it's working now!

**Comment by OnThePull** [comment]
Thank you all for your help!

**Comment by curtisdelicata** [comment]
No problem. Can you remember what fixed it?

**Comment by OnThePull** [comment]
I re-imported the database, it could have been that.

**Comment by curtisdelicata** [comment]
Ok great that it works for you.
