### ISSUE TITLE
Cannot upload new pet images when creating

### ISSUE THREAD

**Issue by AngelwithAdditude** [modulargaming/modulargaming#207]
Once you hit the upload button it just hangs on the processing bar...I create a species,name but cannot upload, plus this error when creating as a user

models/user_pet.colour_id.Valid_Pet::colour_available

**Comment by curtisdelicata** [comment]
I thought I fixed this before 1.0

I will look into this. Thanks

**Comment by curtisdelicata** [comment]
Do you mean you get the second error when creating as a user on pet/create? As I can successfully create a pet on pet/create

**Comment by curtisdelicata** [comment]
Error handling must not be showing correctly. When I upload an 200x200 image it works as expected.

**Comment by curtisdelicata** [comment]
I had to click complete then return and refresh and it shows the colours.

**Comment by curtisdelicata** [comment]
It does not seem to be uploading. I will look into porting the code used on Item module (Kohana Image Module) and see if this fixes it. I tried manually creating directory or using an if with mkdir but it does not upload.

**Comment by curtisdelicata** [comment]
https://sourceforge.net/projects/modulargaming/files/latest
