### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#21]
We should have a class to use pagination for database results in the view.

**Comment by curtisdelicata** [comment]
What are the options?

Should we write from scratch or is there any existing modules we could use?

**Comment by curtisdelicata** [comment]
https://github.com/dari88/Pagination-Module-for-kohana-3.3

**Comment by curtisdelicata** [comment]
https://github.com/webking/kohana-pagination

**Comment by curtisdelicata** [comment]
The last one seems the better option as it is based off the offical Kohana Pagination just modified to work with 3.3

**Comment by curtisdelicata** [comment]
I have forked the offical Kohana Pagination and Kostache Pagination Helper.

I have updated both for 3.3 but there still seems to be errors to fix.

https://github.com/modulargaming/kostache-pagination-helper
https://github.com/modulargaming/pagination

**Comment by Hinton** [comment]
Should pagination use query_string or routes?

Query string is the easiest but routes might look better.

**Comment by curtisdelicata** [comment]
Routes is the best way as that is how we are supposed to do it? /forum/category/2/page/2

**Comment by Hinton** [comment]
Sounds good, we have to rename the action to page in that case.
