### ISSUE TITLE
Adding New Role(s)

### ISSUE THREAD

**Issue by JellyTale** [modulargaming/modulargaming#214]
Upon trying to add a new role and clicking "Create" the button changes to "Saving" and doesn't seem to do anything.

**Comment by t1gor** [comment]
Hello, guys.

This issue also applies to the role edit form, not only create. I've just checked this issue and it seems that the form lacks the CRFS.

![screenshot from 2014-02-19 16 51 11](https://f.cloud.github.com/assets/1280013/2212249/3f198764-99b0-11e3-8dd8-6da1c87a81fa.png)

Unfortunately, I am not a Kohana expert and still can not find the form view :( But, if someone could suggest me the file, I could fix it.

Hope this helps,
Igor

**Comment by happyDemon** [comment]
https://github.com/modulargaming/user/blob/master/templates/admin/user/role/index.mustache

That's the template file ^^

**Comment by curtisdelicata** [comment]
{{csrf}} was missing from the value=

I also added the span class as that is what is in the other template.

https://github.com/modulargaming/user/blob/develop/templates/admin/user/role/index.mustache

**Comment by curtisdelicata** [comment]
It is in develop branch, checkout develop to test. It appears to work.

**Comment by t1gor** [comment]
Thanks, guys, I will :+1:
