### ISSUE TITLE
Ugly user shops error

### ISSUE THREAD

**Issue by JellyTale** [modulargaming/modulargaming#216]
I wouldn't say this is as much of a functionality issue as much as a cosmetic issue.

If I am to navigated to a nonexistent shop (By default you could try: /modulargaming/shops/6) I am greeted by a "No shop found" error, which is exactly what should be happening.

However when navigating user shops, if I go to /shop/1 (Also doesn't exist by default) I get given a ugly Kohana error, instead of a "Shop Not Found!" box.

567                 }
568             }, $portion);
569 
570             if ($required AND $missing)
571             {
572                 throw new Kohana_Exception(
573                     'Required route parameter not passed: :param',
574                     array(':param' => reset($missing))
575                 );
576             }
577

**Comment by Hinton** [comment]
Fixed, https://github.com/modulargaming/item/commit/1502c48865b8f1ccaa691cd6b5ce3f0f0bf66a2b.
It now shows a 404 error page instead.
