### ISSUE TITLE
Messaging system

### ISSUE THREAD

**Issue by JellyTale** [modulargaming/modulargaming#218]
Once again: Not bugs, but just things that might need changing.
1. Users can message themselves. While not affecting the messaging system's ability to function, it's not a nice feature to have.
2. When clicking on "Reply" it would be nice if the user didn't have to go and fill in the information of the person they're replying to. Perhaps if the script could just parse the username of the sender into the form that'd save a lot of time.
3. If a user who doesn't exist is entered into the Receiver form then it takes the sender to a "Page not found" error. What I'd suggest is doing username checking on the page when they enter a user into the Receiver text box and if that user doesn't exist, blanking out the Send button.

**Comment by Forkin** [comment]
It would be nicer if the reply was sorta like facebook's messaging system, where the replies go underneath the message.

For an example:

Admin Message: Hello
User Message: Hi there.
Admin Message: Can I help you?
User Message: Not even the universe can help..

**Comment by Hinton** [comment]
Thread based messaging might be a better solution, it should be a feature request however. All the issues mentioned in the first post has been fixed.
