### ISSUE TITLE
Shop Restock

### ISSUE THREAD

**Issue by Forkin** [modulargaming/modulargaming#223]
When adding an item to be restocked it gives the item ID as "0" and the item name as "null" preventing you from editing the item as well if you input an invalid item name.

Also, editing the item that is suppose to be restocked doesn't work, and the "next_restock" row is "0" meaning the items will never restock. If this "next_restock" row is suppose to be a timestamp[?] and when it meets the timestamp, the item never restocks.

**Comment by Hinton** [comment]
The problem was that the table had no primary key and ID was not auto_increasing. The items would then receive the ID 0 and nothing would work.
