### ISSUE TITLE
Custom error pages

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#24]
We should extend the HTTP_Exception_ classes for custom errors paged instead of the default error pages when in Production environment.

**Comment by curtisdelicata** [comment]
http://kohanaframework.org/3.3/guide/kohana/tutorials/error-pages

Follow the above link but needs to be modified for Kostache.

**Comment by Hinton** [comment]
Opening this issue again, we want to have different kind of error pages.

403, permission denied should display a login page (if he's not logged in, otherwise display a regular error page), HMVC request to user/login?
404, should display some helpful information that can help the player find the resource he is looking for, search?

**Comment by Hinton** [comment]
There are a few ways we can approach this, I'm thinking we should delegate it and have a controller with HMVC requests from the HTTP exception handler. If the action is not found (action_code) it should display the generic error page otherwise use the action.

**Comment by curtisdelicata** [comment]
Sounds good. Feel free to proceed.

**Comment by Hinton** [comment]
Creating a reliable custom error pages was harder than I believed. The current system uses a Kohana_Exception class in application/. It must be in application/, as kohana does not load modules directly.

Kohana_Exception attemps to create a request to error controller and call method 500. It does so by manualy creating a request, response and controller objects, as calling it using HMVC (request->execute) created a recursive loop. It is impossible to catch exceptions when using HMVC.

If the controller gives an exception, such as the database being down (Session_Exception), or for some other reason it fallbacks to a traditional View::factory('error/fallback').
