### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#27]
We need a way to email users, welcome email, password reset, notifications.

There are a few existing solutions, mostly wrappers around swift mailer.

**Comment by curtisdelicata** [comment]
https://github.com/michal-m/kohana-modules-swiftmailer

**Comment by curtisdelicata** [comment]
https://github.com/digitaljohn/kohana-email

**Comment by curtisdelicata** [comment]
I have forked Kohana Email. Created new branch 3.3/master and updated SwiftMailer. I will add the submodule now.

**Comment by curtisdelicata** [comment]
https://github.com/modulargaming/email

**Comment by curtisdelicata** [comment]
I have tested with:

 $email = Email::factory('Hello, World', 'This is my body, it is nice.')
    ->to('person@example.com')
    ->from('you@example.com', 'My Name')
    ->send();

It successfully sent me an email
