### ISSUE TITLE
Messaging system

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#28]
Users should be able to view, delete, send and receive messages.

Should we wait until forum and use private topics for messaging? So that it will support multiple recipients.

**Comment by curtisdelicata** [comment]
This needs to be rewritten? Should we use private topics with the existing forum code?

**Comment by curtisdelicata** [comment]
May depend on #65

**Comment by curtisdelicata** [comment]
We should use private topics which are in a private category 'messages'.

This way we can handle multiple recipients and you can add new members to the private topic. Messaging should show the private topics you are subscribed to.

**Comment by curtisdelicata** [comment]
Might make more sense for messages to be in category 0? Separate table for users which are in the conversation.

Regardless of how we implement it, messages should be threaded and show message history and you should be able to have multiple recipients.

We need to decide on how messages should work. Please discuss.

**Comment by happyDemon** [comment]
Maybe we should add a 'report message' feature, so moderators get notified of any mishaps when messaging.

I think it might also be best that we implement a soft-delete, meaning it won't show up for the users, but moderators would still have access to it. A cron could be run to delete X months old deleted messages.

**Comment by Hinton** [comment]
If I remember correctly we had soft delete in the old modulargaming, not quite sure how we implemented, report message feature seems like a good idea.

**Comment by curtisdelicata** [comment]
I think we should keep messaging and forum separate? Maybe use similar code? Or if we are using the same code shouldn't we use forum instead?

**Comment by curtisdelicata** [comment]
@Lewis

**Comment by curtisdelicata** [comment]
Messaging should use type a head AJAX for sending to username. Maybe reply should show username too. I think we should keep the id for internal use.

**Comment by Hinton** [comment]
We could use http://jasny.github.com/bootstrap/javascript.html#typeahead
We should send the username in the post, and look up the user object serverside.

**Comment by happyDemon** [comment]
typeahead comes bundled with twitter bootstrap.

I've prepared a base for this, well I already implemented it (inventory -> gift to user uses typeahead to retrieve possible username).
it sends an ajax request to the search controller which returns a list of usernames.

https://github.com/hinton/mg/blob/master/modular-gaming/item/assets/js/item/inventory/index.js   --> starting line 86
https://github.com/hinton/mg/blob/master/modular-gaming/core/classes/Controller/Search.php
