### ISSUE TITLE
Forum - Locked-down 'News' boards

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#33]
Admins start a thread and it shows up as a news item. Subsequent posts show as comments!

**Comment by curtisdelicata** [comment]
Should we use a policy to do this?

Policy_Forum_Topic_Create 

if category = locked {

if role = admin { return true; }
 else {return false;}

}

if category = unlocked
{
return true
}

**Comment by Hinton** [comment]
Yep, this should belong to the policy.
