### ISSUE TITLE
Forum - HTML Editor

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#35]
Full power of HTML can be utilized for post mark-up - safely. A rich text editor is available to make adding flair to your post easy.

We could use HTML Purifier and TinyMCE? What are the options?

**Comment by curtisdelicata** [comment]
http://jhollingworth.github.com/bootstrap-wysihtml5/

**Comment by curtisdelicata** [comment]
http://xing.github.com/wysihtml5/

**Comment by Lewis** [comment]
I have added WYSIHTML5 for the forum and messages textareas. Should we allow HTML with something like HTML Purifier or should we parse BBCode?

**Comment by curtisdelicata** [comment]
I think we should use HTML Purifier.

**Comment by curtisdelicata** [comment]
At the moment it seems to be already filtering it. HTML Purifier would be best.

**Comment by curtisdelicata** [comment]
http://forum.kohanaframework.org/discussion/480/html-purifier-why/p1

it seems that HTML Purifier has a lot of files. It must be cached so must not be too bad?

**Comment by curtisdelicata** [comment]
http://forum.kohanaframework.org/discussion/11260/html-purifier-xss-proper-handling/p1     

" If you use something like KOstache, it does this automatically for you."
