### ISSUE TITLE
Forum - Post counts

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#37]
User post counts should be shown on threads and posts.

**Comment by Hinton** [comment]
The best way to manage this would be a post_count field in the user table that gets added one per post. We might also want to subtract if a post is removed and have a recalculate feature.

**Comment by curtisdelicata** [comment]
What about caching a count using find_all on forum_posts where user_id= poster_id?

**Comment by Hinton** [comment]
How would we cache it?
We could have a recalculate function that we run every time we add/remove a users posts, might be better than adding/subtracting.

**Comment by curtisdelicata** [comment]
Recalculate function sounds ok.

How do other forum software calculate it? E.g. PHPBB
