### ISSUE TITLE
Forum - User titles

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#38]
Threads and posts should show the user title. Should this be their role?

**Comment by Hinton** [comment]
How do we want to display user titles, should it be an image, text?

**Comment by curtisdelicata** [comment]
Text is fine.

**Comment by curtisdelicata** [comment]
User titles won't display, I am unsure why. Please can someone take a look.

**Comment by curtisdelicata** [comment]
I forgot to update the old user account to have a title_id

It works as expected. Closing issue.
