### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#4]
Email a new password.

**Comment by curtisdelicata** [comment]
What are the options on how to send mail? Should we use the built in commands or look into using other modules such as SwiftMailer.

**Comment by curtisdelicata** [comment]
Depends on #27

**Comment by curtisdelicata** [comment]
Email works. This can now be worked on.

**Comment by Hinton** [comment]
Wondering a bit about how the database should be designed.

I could add a field called reset_token, but it feels cluttered if we ever need a similar solution in the future.

Kohana Auth provides the user_tokens table, it's used by the remember me feature, and would be a better solution. However it doesn't provide a way to have "multiple" token types and has some extra data we wont need (like user_agent).
We could tweak the table, rename user_agent to data, add a type field and update the Auth module accordingly.

Any suggestions on what approach we should do? I consider the second approach to be slightly better than the first.

**Comment by curtisdelicata** [comment]
Using user tokens sounds best. User agent is useful?

**Comment by happyDemon** [comment]
Could we have a user_settings table  
id, user_id, property, value

We could store data there that we don't need on every page load (e.g. forum signature, reset_token, avatar, ..) 
the property could be: forum.signature, reset, avatar.

This would open up posibilities when developing further; quests could store which level the user's at (quest.{id}.level)

**Comment by Hinton** [comment]
Having a user_settings table sounds like a good idea, would remove module stuff from the user table. However we would need a good way to implement it, it's not reasonable to run an additional query to load such data.

Consider the following case.
Browsing a forum topic, for each post in the topic we would have to load the avatar and signature. That's 1 additional query per post.

```
1 query to load the topic with categories joined.
1 query to load all posts joined with users
count(posts) queries to load the additional user data
```
