### ISSUE TITLE
Inventory system

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#42]

**Comment by Hinton** [comment]
Content of our discussion:

**Items table**
- id
- name
- description
- category_id
- data

**shop_items**
- store_id
- item_id
- quantity

**item_crafting**
- id
- name
- description
- required_items
- generated_item

Example format of **data** column in items_table:

```
{
    {
        "action": "paint"
        "data": {
            "color": "1"
        }
    },
    {
        "action": "heal",
        "data": {
            "amount": "10"
        }
    },
    {
        action: "somethingLong",
        "data": {
            "param1": "lol",
            "param2": "hax"
        }
    }
}
```

**Item class:** (extend it)

```
class Item {

    function action(user, pet, array data)

}
```

This format will allow a single item to run multiple items actions.

**Comment by happyDemon** [comment]
I've currently have this structure down

_items_
- id
- item_type_id
- name
- description
- image
- status (draft|released|retired)
- unique //if the user can only have on copy of this item
- transferable  //if the user is able to send the item to other users
- command //contains data that will be used when consuming an item

_item_types_
- id
- name
- action //the text displayed to consume the item
- default_command //an item could have multiple consume commands, the item type just defines the default one for consistency
- img_dir
- load_pet_list //if a pet list should be loaded when consuming the item

_user_items_
- id
- item_id
- user_id
- amount
- location
- parameter //e.g. when location is shop this value would be the price

_Item commands_
These would be split into classes, commands would be callbacks to specific methods.

Item_Pet::feed
Item_Pet::play
Item_Pet::paint

Item_General::cook //for recipe

Item_User::move //to safebox, usershop,...
Item_User::delete
Item_User::gift

This is stil a draft and will be worked out further

**Comment by happyDemon** [comment]
For crafting I'd recomend a small change in DB structure
_item_recipes_
- id
- name
- description
- crafted_item_id

has_many through:
_item_recipe_requireds_
- item_recipe_id
- item_id

**Comment by Hinton** [comment]
Hmm, seems like a good structure, maybe the command classes should be called Item_Action_\* or Item_Command_*.

In the forum we use topic_id rather than forum_topic_id, perhaps we should use type_id rather than item_type_id.
item_type_id is more detailed, but I don't think it's easy to confuse if we only use type_id.

**Comment by happyDemon** [comment]
It's a naming convention used by the ORM in its relations in other words it would be looking for the primary key of item_types table, but changing it wouldn't be a problem ^^

You're 100% right on the item action/commands name, they'd need to be put in a proper dir, let's go with Command?

**Comment by Hinton** [comment]
Command sounds fine. What would default_command be used for? And should parameter be parameters in user_items, in case we want to store multiple parameters (using json or has_many).

**Comment by happyDemon** [comment]
it would dictate any item that has its item type is required to use this command. An item isn't limited to just one command.
e.g. neopets used to have an ommelette from which you could take multiple bites. 2 actions would be performed: pet's hunger level is changed and the item is replaced with another.

**Comment by Hinton** [comment]
True, but what about potions. Won't that require us to have multiple potions categories if they all do different things?

**Comment by happyDemon** [comment]
I would see potions affecting stats, it's all about defining the potion command. You would pass which stat(s) to influence by how much
They shouldn't be limited to just changing one stat

**Comment by Hinton** [comment]
Well, I was more thinking of uhm, something that will be in the same category but will do different things, health and energy potions perhaps? They would call 2 different commands but should still be in the same category, or perhaps I am misunderstanding it, and we should have an item_category for organizing items in inventory and shops?

**Comment by happyDemon** [comment]
Item_Command_Pet::potion could get their command assigned like this

```
{
  "action": "potion",
  "stats": {
    "hp": "+1"
  }
}
```

other potion

```
{
  "action": "potion",
  "stats": {
    "mp": "+1"
  }
}
```

and another potion changing multiple stats

```
{
  "action": "potion",
  "stats": {
    "int": "+1",
    "spd": "+1"
  }
}
```

item commands be bound to several item types
Food: Item_Command_Pet::feed
Drinks: Item_Command_Pet::feed

**Comment by happyDemon** [comment]
how would the item_category work though? wouldn't that be the same as item_type?

**Comment by happyDemon** [comment]
I'm nearly done with the inventory, all that's left is some making some templates(view&consume), debugging and pagination. If there's anything you guys wantto see added, tell me ^^

**Comment by curtisdelicata** [comment]
I noticed you have a command for pet transform (change specie) but could not see one for changing the colour?

**Comment by happyDemon** [comment]
it's called Pet_Paint, not implemented at the moment though
