### ISSUE TITLE
Inventory - User shops

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#46]
- [x] Index
  - Upgrade the user shop's inventory size (if allowed by admin)
  - Update the shop's title and description
- [x] Create (charge a creation fee if it's set in the config)
- [x] Stock
  - Inventory: delete or modify item's price
- [ ] Logs
  - Collect the shop's earnings
- [x] View a shop
  - Buy an item

**Comment by happyDemon** [comment]
I should probably add a HTML whitelist filter for the usershop description, aswell as do some xss cleaning.
Next up, checking if everything works.

I can't really implement user shop logs before the Log helper we were discussing is finished, who's working on this? @hinton layed out some basic functionality a while ago.

**Comment by curtisdelicata** [comment]
You can use HTML Purifier for XSS cleaning. Simply call Security::xss_clean($variable).

The best way is probably how we do it for forum in the model.

```
   public function filters()
    {
            return array(
                    'content' => array(
                            array('Security::xss_clean'),
                    ),
            );
    }
```

**Comment by happyDemon** [comment]
Thanks man, from doing some reading up on HTML purifier it seems that they already whitelist quite some HTML tags.

Although I'm a bit worried, we're using a 2 year old version of HTML purifier (through shadowhand's repo), I can't really access the modules tree here on github right now to actually check the version, but it seems really outdated.

**Comment by curtisdelicata** [comment]
It is the best white list as far as I know.

I forked shadowhands module, updated it for 3.3 and I also downloaded the latest HTML Purifier to the vendor folder so it is up to date.

**Comment by happyDemon** [comment]
ok :D I was basing myself on the version shadowhand had hardcoded in his class, so thanks for taking away my worries :D
