### ISSUE TITLE
Inventory - Crafting

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#47]
Create new items with recipes and ingredients
- [x] Admin page for managing recipes
- [x] Assign items as recipe
- [ ] Inventory cook-corner

**Comment by happyDemon** [comment]
How are we going to be doing this? the same as kitto kitto, with a page where all the user-owned recipes are displayed, so the user can start crating from there on out?

**Comment by curtisdelicata** [comment]
The same as Kitto sounds good.

**Comment by happyDemon** [comment]
Started on this, need to brush up the interface a little before I start adding the ajax alternative. Nearly complete  though ^^
