### ISSUE TITLE
Inventory - Trading

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#49]
Trading - be able to send and receive items

**Comment by happyDemon** [comment]
- [x] Index - browse trading lots
- [x] Create - show items to create a lot
- [x] - Process - create a lot
- [x] Lot - View a lot (show bids if owner, show player's bid if bid was made)
- [x] - delete - Delete the specified lot
- [x] Bid - show items to bid on a lot
- [x] - Process - actually bid on a lot
- [x] - Accept - accept a bid
- [x] - Reject - reject a bid
- [x] - Retract - take a bid back
- [x] Bids - show all the bids the player's made
- [ ] Search - search through trades
