### ISSUE TITLE
Javascript and CSS before function

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#52]
We need to be able to specify certain Javascript and CSS files only on certain pages. Can we do this using before function?

**Comment by Hinton** [comment]
Do we really want that?

Considering that css and js gets cached after the first load.
We have my assets module, https://github.com/hinton/assets for minifying and combining css & js.

**Comment by curtisdelicata** [comment]
I guess if they get cached after first load it would not matter if we load them on every page.

Assets module might be good.
