### ISSUE TITLE
Admin - Creating/editing/deleting items

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#57]
- [x] Item command autocompleters
  - Recipe
  - Pet color
  - Pet specie
- [x] Item command validation
- [ ] Redo Item recipe validation
- [x] Bug: opening modal from search says creating
- [x] Bug: deleting from modal fails

**Comment by happyDemon** [comment]
as you can see, i pushed some initial code for the item admin

Item commands aren't included yet, still need to figure out how exactly I'm going to implement them.

So right now you've got your basic add/edit/delete functionality, along with a new auto-complete item search. The whole interface being in driven by ajax requests.

**Comment by Hinton** [comment]
Regarding ajax request, I was thinking we should use the Kohana is_ajax function to determine if we want to render with the template or without.

I doubt we are going to need ajax fallbacks, but if they won't cost us any extra work it wont hurt to provide them.

It's also bad to disable CSRF in admin panel, as it would open up for cross site attacks.

**Comment by happyDemon** [comment]
I know, I just turned them off untill we can generate them for use with the ajax interface. Since they're currently generated on a pageload-basis they wouldn't really be of any use when the form could be used multiple times on 1 pageload. I'm just thinking how we can work around this without doing too much requests.

I'm sure we can atleast trust owners to have up-to-date browsers so they certainly wouldn't be needed in the admin.

**Comment by Hinton** [comment]
True, was more thinking of smartphones and other smaller devices, might be bothersome displaying a modal in such a small resolution.

I was considering sending html content and render it without the template if it was ajax and with template if its a regular request. Json is smaller but you have to build the html using js in that case, we should consider using mustache clientside in that case.

**Comment by happyDemon** [comment]
that's a good option :D

**Comment by Hinton** [comment]
Not quite sure what you are refering to, there was several ideas in the previous post.

Sending it as rendered html or use mustache to generate it from json?

**Comment by happyDemon** [comment]
Rendering it clientside with mustache, sorry was in the middle of making dinner, skimmed a little.
We could tie it in with jquery mobile or something similar when detecting a mobile browser.
We would only be sending the template once, using less bandwith.

Although we'd really need to put in somework into the admin module to get this working properly.

**Comment by Hinton** [comment]
Yep, we should create a solid admin module that minimizes the work for each page. 

We should be able to share the mustache templates, how about precompiling the needed mustache templates and serve it as a js file. We would need a way to precompile them however, not sure if there exists a php script with that feature.

**Comment by happyDemon** [comment]
I don't think the template files should prove to be a problem, hold on, we need to create a new ticket for this discussion

**Comment by happyDemon** [comment]
opened #79 for further discussion about the admin specification

**Comment by happyDemon** [comment]
Allrighty, nearly done with this one.
All that's left to do is validate the commands that are being sent when saving, implement a few more autocompleters for the item commands and do some necessary controller code clean up, merge validations in some places.

Any last minute requests for the item admin?

**Comment by curtisdelicata** [comment]
Sounds good, I can't think of any requests.

**Comment by happyDemon** [comment]
Phew, what a 9 days it was o.O this is finally feeling done, just need to redo the way item recipes are validated and I can move on to the user-portion _yay_
