### ISSUE TITLE
Forum - Polls

### ISSUE THREAD

**Issue by Lewis** [modulargaming/modulargaming#64]
Topics should be able to have a poll added to it.

**Comment by curtisdelicata** [comment]
We should use a new table forum_polls for this?

**Comment by curtisdelicata** [comment]
I've pulled the recent changes but I get an error:

The requested URL forum/topic/1/poll was not found on this server.

**Comment by Lewis** [comment]
I haven't added any controllers or views for polls yet.

**Comment by Hinton** [comment]
Opening this issue again.

The poll action in Topic is quite messy, and we should consider moving it to it's own controller, or split it into multiple actions.

**Comment by Lewis** [comment]
Ok.

**Comment by curtisdelicata** [comment]
#150
