### ISSUE TITLE
Log Notification System

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#67]
We should have an event log. Things such as your pet was attacked while you were off line or someone bought an item from your shop.

**Comment by curtisdelicata** [comment]
It should be a function like bread crumbs so we can do Log::add('Description')

**Comment by Lewis** [comment]
User id needs to be passed too. For example when an item is bought from user shop you need to set buyer and seller log

**Comment by Hinton** [comment]
Table structure

**Notifications**
id
user_id
title??
message
type (success | alert | warning)?

There might not be a need to have a title, but it could be nice if we plan on sending emails when a user gets a new notification.

**Comment by curtisdelicata** [comment]
Yes that looks good. Title is a good idea.

**Comment by happyDemon** [comment]
I think we could benefit from splitting this up into 2 tables, one for logs, one for notifications.
The logs would have more information that moderators could use, while the notifications would have some small informational info and easily be deleted.

**Logs**
id
user_id
location //the controller route of where this happened
time  //ORM created property
message
params  //these could be used to store all kinds of data e.g. when a user bought an item from a usershop it could store the item's id, price, user shop id

**notifications**
id
log_id
user_id
title
message //this one would come preparsed
type (success|alert|warning)

We could still expand on this idea of logging and notifications I think

**Comment by Hinton** [comment]
Seems like a good suggestion, time to spy on players! :D

**Comment by happyDemon** [comment]
haha, at misticpets they had something similar, it's made checking false claims easier or made catching cheating players a lot easier ^^

**Comment by curtisdelicata** [comment]
Will we have a helper to add log and notifications?

**Comment by happyDemon** [comment]
Kohana has interfaces for this, so we could hook it in there

http://kohanaframework.org/3.3/guide-api/Log

**Comment by curtisdelicata** [comment]
I thought that was for system logs and not logs of actions carried out by users.

**Comment by happyDemon** [comment]
The default instance belongs to the system, we can add our own instance (and writer) to cover our part of the framework.

**Comment by curtisdelicata** [comment]
Good idea.

**Comment by happyDemon** [comment]
I have an example of how we could implement it : https://github.com/hinton/mg/blob/master/modulargaming/item/classes/Item.php   lines 188-247

**Comment by happyDemon** [comment]
if you want to see it in-action:
https://github.com/hinton/mg/blob/master/modulargaming/item/classes/Controller/Trade.php

check the bid, accept, reject, retract, delete actions, they log and notify
