### ISSUE TITLE
Event system

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#70]
We need a way to only use certain code if a module is loaded.

Example is the pets on user profile. They should only be displayed if the pet module is enabled.

**Comment by curtisdelicata** [comment]
Maybe better if pets module contains the code and it is automatically loaded on user profile page.

**Comment by Lewis** [comment]
How would that work?

**Comment by Hinton** [comment]
There are a bunch of event modules available for kohana.

But a typical workflow would be to inside user profile we call an event and pass along an array with tabs, a module could then add a "Tab" class instance by adding a hook to the event.

And in the view we render the tabs by looping them and calling render, or something along that?

**Comment by curtisdelicata** [comment]
That sounds like how we should do it. What are our options for event modules?

https://github.com/thinkclay/Kohana-Event-Module - I think this should work if we rename the files for Kohana 3.3
https://github.com/samsoir/kohana-event - I am unsure if it will work correctly.

Are there any others available?

**Comment by curtisdelicata** [comment]
https://github.com/BRMatt/Kohana-Dispatcher
https://github.com/Zeelot/event
https://github.com/ollym/event

**Comment by curtisdelicata** [comment]
https://github.com/modulargaming/event

**Comment by curtisdelicata** [comment]
I believe we should use https://github.com/modulargaming/event as it is simple and works with Kohana 3.3 without changes. I am open to other options.

Please discuss what you think about this.

**Comment by happyDemon** [comment]
@curtisdelicata the one you cloned wouldn't be optimal to register several events to a handler, that one just registers an event that will be executed lateron.

I quite like laravel's Event handler (https://github.com/laravel/laravel/blob/master/laravel/event.php - http://laravel.com/docs/events).

the profile controller code could have something like:

``` php
$tabs_list = Event::fire('profile.tabs', array($user));
```

The pet module's init.php would have

``` php
Event::listen('profile.tabs', function($user){
//get pets
//fill mustache tab view
return array('tab_title' => 'Pets', 'tpl' => 'tpl.mustache', 'data' => $pet_mustache_view);
});
```

This would make sure $tabs_list is filled like this:

``` php
array(
0 => array('tab_title' => 'Pets', 'tpl' => 'tpl.mustache', 'data' => $pet_mustache_view),
)
```

making it easy to iterate and build the tab interface

**Comment by happyDemon** [comment]
it just returns the first element of an array (http://laravel.com/api/function-head.html)

**Comment by Hinton** [comment]
Hmm, seems to be a better alternative than the Kohana version, it doesn't seem to be hard to port either, as it only depends on one laravel specific function.

Edit: Accidentally deleted the message.

**Comment by happyDemon** [comment]
we'd just have to rename the head function to reset and that's it to port it over, simple as pie

**Comment by Hinton** [comment]
The only disadvantage I can see is if a module would want to edit another modules tab somehow, as it no longer have direct access to all tabs compared to the Kohana version where you are forced to send the data as an parameter.

**Comment by happyDemon** [comment]
it would be easy enough to just check the tab_title property when processing the results, no? if we've already got the tab_title property in a list, wouldn't want to change its result with something that came later (or the other way around)

or add a data object as argument, that stores this, no output would be needed anymore.

With data object I would imagine a Tab class where you would add your tab to in your event, all checks could be done by the class.

**Comment by curtisdelicata** [comment]
I have deleted the fork at modulargaming/event

I have given you both full access to the Modular Gaming organization on github. You can add repositories now if needed. Laravel's Event handler sounds interesting.

**Comment by curtisdelicata** [comment]
This can now be closed?

**Comment by Hinton** [comment]
Close it after we got the event class in our repo.

**Comment by curtisdelicata** [comment]
Good idea

**Comment by happyDemon** [comment]
I sneaked it in in one of my last commits

**Comment by Hinton** [comment]
We should add a docblock containing where we got it and their license.

**Comment by Hinton** [comment]
I noticed that we might have problems with the event module in HMVC requests. Events created in the request will be valid in the next sub-request, something we might want to avoid if possible.

**Comment by happyDemon** [comment]
HMCV only covers extending classes, events are just functions that are created to be executed at one point, only once, not to be reused.

I don't really see a point in extending them or how we could gain anything from it at this point.
But I could be missing your point

**Comment by Hinton** [comment]
I was thinking what would happen if we added an event in the main-requests controller that also gets executed in the sub-request. Not sure if there are any such case. As events probably won't be added in controllers, only fired.
