### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#71]
Should Dashboard look like the user profile?

Or should we redirect dashboard to user/view/$current_user

Or should we merge profile and settings?

**Comment by Lewis** [comment]
I think it should be the same as other users' profiles.

**Comment by Hinton** [comment]
/user/ should redirect to the current logged in user. (/user/view/id)

Welcome should be split into 2 parts, one for logged out users and one for logged in.
The logged in should be the dashboard and show a user his notifications, pets, forum posts or whatever is important.

**Comment by curtisdelicata** [comment]
I think I have confused you all with the way I wrote it. I meant should the profile link redirect to the standard user/view 

Dashboard needs to be the default page for logged in users.

**Comment by curtisdelicata** [comment]
I changed the profile link on the drop down to go to /user/view/user_id

I have left /user as the Dashboard. Should /user be the default logged in page?
