### ISSUE TITLE
Users online

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#72]
There should be a list of users online. Maybe a link in the footer.

**Comment by curtisdelicata** [comment]
Should we check if last_login < x amount of time (30 minutes maybe) show the users.

**Comment by Hinton** [comment]
That wont work, if a user idles with the browser open he will expire the 30min time. We could check the value on every pageload and update if needed.
But is a "users online" feature something we are going to need?

**Comment by curtisdelicata** [comment]
I guess your right, that would be the right way. I don't think it would be worth the extra queries, this should be optional and not required.

Closed.
