### ISSUE TITLE
Forum - Private categories

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#73]
We should have private categories for moderators and admins.

**Comment by Hinton** [comment]
Should we have an int public inside the forum_category table?

Should a category be open for multiple roles or just one, if only one we could have a role_id column while if we want multiple we would need a separate table.

It depends slightly on how we want roles to work.

**Comment by happyDemon** [comment]
I'd definitely go for a seperate table since we don't want to hard code in staff groups, we could do this in combination with a public field, if it isn't public only than we'd check for the permissions to save on query load.

**Comment by curtisdelicata** [comment]
A public field sounds the right way.

**Comment by curtisdelicata** [comment]
Closed for now.
