### ISSUE TITLE
Modular gaming - specific module folder proposal

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#76]
Hey all,

I just got on board, Curtis was nice enough to add me, I'm Maxim Kerstens, I used to go by Zenk0 (helped out here and there with the old MG).

I'll introduce myself personally soon, but for now I had a small proposal I would like to discuss with you.

I see that you guys are putting the Modular gaming -specific modules in APPATH/modules,

If we're following Kohana's naming conventions I would advise against this, the application folder should only contain application-specific code (that would be any developer that adopts the modular gaming framework, not us).

I also wouldn't recomend moving these modules to MODPATH, since we'd want to differentiate from Kohana-specific modules. 

What I would suggest is creating a folder in DOCROOT called 'modular_gaming' and place all the code we create there.

All our code would be in 1 place, new developers would know where to look for MG specific code, keeping APPATH free for their own game-specific code.

This would be a small change, I hope I can get you guys behind this ^^

**Comment by happyDemon** [comment]
I went ahead and created a new branch to show you the implementation, it's minor and could be easily merged or deleted depending on the response.
https://github.com/hinton/mg/tree/proposal-dir

**Comment by curtisdelicata** [comment]
I did not know about Kohana's naming conventions said that application/modules is wrong.

Do you mean that we should move everything under application to DOCROOT/modular_gaming

I agree with your proposal, ask Oscar and if he agrees then please proceed with merging.

**Comment by Hinton** [comment]
Hmm, that's one way to solve it, I was considering creating a Kohana folder and place system and Kohana modules in it while keeping modules for mg related code.

Not sure what approach would be best, it makes sense to keep our "libs" (Kohana & Kohana modules) in a seperate directory.

It seems like you changed base_url in the branch, it should automatically have detect the correct url.

**Comment by curtisdelicata** [comment]
What about a directory called framework?

**Comment by curtisdelicata** [comment]
Actually modular_gaming is probably more obvious?

**Comment by Hinton** [comment]
Framework would be confusing, might be best to go with @happyDemon suggestion.

**Comment by happyDemon** [comment]
I know, I just made a commit to fix it.

@hinton you're suggesting a dir structure like this:

DOCROOT/
-application
-assets
-modular_gaming
-kohana/
--system
--modules

That would be easy enough & even less clutter

It's easy to change in DOCROOT/index.php

**Comment by curtisdelicata** [comment]
@happyDemon I agree with your suggested directory layout. However I am unsure if we should move system and modules yet.

**Comment by curtisdelicata** [comment]
what about using modules/modulargaming
modules/modulargaming/core
modules/modulargaming/forum etc

**Comment by Hinton** [comment]
@curtisdelicata Well while it would work you wont get as much separation and it's slightly confusing. Where would third party MG modules go?

Technically they should be in modules/modulargaming but they aren't actually a part of our core packages.

Oh and welcome aboard @happyDemon, forgot to say hi before.

**Comment by curtisdelicata** [comment]
Other modules use hyphens instead of underscores. Would modular-gaming be better than modular_gaming?

**Comment by curtisdelicata** [comment]
I have deleted the branch as we have finished with it.

**Comment by curtisdelicata** [comment]
"@curtisdelicata Well while it would work you wont get as much separation and it's slightly confusing. Where would third party MG modules go?

Where would third party modules go now? application/modules? modular-gaming/ ?

**Comment by happyDemon** [comment]
Third party modules containing Kohana specific code should still go into modules, while modular gaming specific modules would go into modular-gaming. to keep things simple

**Comment by Lewis** [comment]
Is there a reason we need a hyphen or underscore? I think it looks better as modulargaming

**Comment by curtisdelicata** [comment]
This issue can now be closed.
