### ISSUE TITLE
Signing off commits

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#77]
Should we sign off commits using the -s switch?

I think it may be a good idea. However the Developer's Certificate of Origin in the license may be good enough on it's own.

**Comment by Hinton** [comment]
According to http://wiki.eclipse.org/EGit/User_Guide/Commit#Signing_off_commits, "The purpose of this signed-off-by information is not defined by Git but by the team using Git. Some teams use this information to record who has reviewed a certain commit. Other teams use the signed-off information to record that a commiter agreed to certain standards/rules. E.g. you may have to sign-off your own commits to state that you have read and understood the license-specific rules of your project."

And http://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for.

It seems like we are free to choose however we want to use sign-off and if we want to use it.

I think it's easier to not sign-off commits as the "Developer's Certificate of Origin 1.1" should be enough if anyone submits a pull request.

**Comment by curtisdelicata** [comment]
Thank you for your detailed response. It makes sense that we should be free to choose.  The new license should be enough.

**Comment by Hinton** [comment]
Should we close this issue?

**Comment by curtisdelicata** [comment]
Yes it can be closed.
