### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#78]
While I was creating the item admin I noticed that it seems like we don't have an asset manager yet.

This one seems interesting, we'd just have to upgrade it to KO3.3 and integrate it into mustache: https://github.com/OpenBuildings/asset-merger

**Comment by Hinton** [comment]
Hmm, it might be slightly overkill, it seems like the module puts everything in the same block, it's recommended to put the script tags just above the body close tag to improve load time.

I wrote an assets module a long time ago, https://github.com/hinton/assets

Well either way if we properly cache it using Fragment as explained in the blog, http://ivank.github.com/blog/2011/11/kohana-assets-done-right/ it should be fine either way.

**Comment by happyDemon** [comment]
Yours seems easier to call and integrate, js and css blocks wouldn't be needed and using .less parsers and the sorts I don't see being used.

Who's going to implement this?

**Comment by Hinton** [comment]
I was going to do it after my exams ended (tomorrow), but you are free to do it if you want.

**Comment by happyDemon** [comment]
haha, I'm swamped today with the item admin, haven't got a clue about Kohana's fragments. I'll leave it up to you if that's ok :D

**Comment by Hinton** [comment]
Perhaps we could use https://github.com/Zeelot/kohana-assets.

It seems like a better approach to use config files rather than a static class (HMVC).

**Comment by Hinton** [comment]
Committed the assets controller from my module, so we can serve assets from modules.

**Comment by curtisdelicata** [comment]
Looks good.

**Comment by Hinton** [comment]
Draft for assets manager class.

Loads assets from config files.

``` javascript
return array(
    'main' => array(
        'stylesheets' => array(
            '/assets/css/bootstrap.css'
        ),
        'javascript' => array(
            '....'
        ),
    ),
    'admin' => array(),
);
```

In development the files should be used as they are, without merging/minifying. And in production they should be merged, minified and cached to /assets/....

**Comment by curtisdelicata** [comment]
I agree with your proposal.

**Comment by happyDemon** [comment]
The debug toolbar needs to be turned off in the asset controller, it's spitting out errors.

How are we going to load the assets when we're dealing with specific assets for a controller:action?

**Comment by happyDemon** [comment]
also, the order javascript files are loaded is very important, we would need a way to tell the collecter you would want to add this js file before/after a different js file.

I'll certainly be needing for the item admin

**Comment by Hinton** [comment]
Would it be enough to support weight, or do we need dependency support somehow?

**Comment by happyDemon** [comment]
I'd love for it to have dependancy support, it would tie in nicely when
defining html through events

**Comment by curtisdelicata** [comment]
Dependency support would be best.

**Comment by happyDemon** [comment]
Added asset loading through config files in the latest commit d40c91d007b6a09f6aa6da4538f899e3df74d842
Even updated the frontend controller to load the essential assets that are needed on every page.

Registering assets would be as easy as calling this in your controller

``` php
$config = Kohana::config('assets.forum');
$this->_load_assets($config);
```

Loading assets can only be done by providing an array, e.g. not a config object.

**Comment by happyDemon** [comment]
e0dac014dc2764cf6abbb6f76e0da516e4600c00 Adds the extra assets needed by the admin, I still need to user admin still needs to loads its asset file, didn't include it in the commit.
