### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#8]
It should be possible to search for users, forum posts, news and more.

**Comment by curtisdelicata** [comment]
We should add the ability to search for users. The rest will need to be added when the features are available.

**Comment by Hinton** [comment]
I was thinking about how to deal with searching, we got 3 methods.
1. Use lucene, https://lucene.apache.org/solr/
2. Use mysql fulltext search
3. Use sql like.

Lucene should give best performance by far but requires running a standalone java application.
Mysql fulltext requires quite a few indexes and has quite large memory usage on large tables, and the tables has to be MyISAM.
Sql like is slow.

Lucene seems like the best alternative.

**Comment by curtisdelicata** [comment]
Do we really want to have to run a standalone java application?

We want to use InnoDB? So MySQL fulltext is not an option.

How slow is SQL like compared to Lucene?

**Comment by Hinton** [comment]
SQL like is way slower than Lucene, we could start with sql like as it will be enough for most sites and move to Lucene once/if we need to.

**Comment by Hinton** [comment]
It has a php version but its much slower than the java version.

**Comment by curtisdelicata** [comment]
We should stick using SQL like for now then.

**Comment by happyDemon** [comment]
There's always a possibility to release a side module later on that would overwrite the default search behaviour (with HMVC it shouldn't be hard to do). Or make the search in to a helper, use a config file to decide on its behaviour.

**Comment by Hinton** [comment]
It should be possible to use a search class with drivers similar to how config does it, was mostly wondering how we should code it for the first release.

**Comment by curtisdelicata** [comment]
I think we should use drivers as suggested. Could they be loaded using events? So we can have item search etc if the module is enabled.
