### ISSUE TITLE
Routing naming standard

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#80]
We need a naming standard for routes, currently I use slash to seperate them, but it feels to similar to urls.

I suggest that we use <module>.route_name. For example login would be user.login.

We should also attempt to use routes as much as possible and avoid catch em all routes such as the default route and admin route. Mostly for allowing reverse routing to be as painless as possible and offer an easy way to directly change for example the login url to /login/ rather than /user/login/.

I know it's easier to just have a catch em all route such as the default but routes should offer us more flexibility in the end.

**Comment by happyDemon** [comment]
I'm all for this, I would include the same standard when naming events.

**Comment by Hinton** [comment]
We should write down a naming standard guide or something for these things, using the userguide module?

**Comment by happyDemon** [comment]
sounds good, if you want, I could take some time next week to sit down and write some about designing admin pages.

It's good to have these kind of developer guides around, makes things much clearer, especially for people prospect developers

**Comment by curtisdelicata** [comment]
I agree with this proposal.

**Comment by Lewis** [comment]
Sounds good.
