### ISSUE TITLE
SQL structure & migrations.

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#81]
The current sql file is quite hard to maintain and detect changes in.

We should split it up and place them inside correct module.

We should also consider using minion-migrations for installation and updates.

I found https://github.com/OpenBuildings/timestamped-migrations as an alternative to minion-migrations.

**Comment by happyDemon** [comment]
seems perfect, I'm willing to write the initial DB migration if we're implementing this

**Comment by curtisdelicata** [comment]
Seems interesting. Is there anyway for it to find the migrations in the modules?

**Comment by curtisdelicata** [comment]
Does this also mean we have a way of upgrading? Users of Modular Gaming could upgrade there database safely using this?

**Comment by happyDemon** [comment]
I think we could hook that functionality in there using Kohana::find_file().
Yup, that's the plan I think :D although I think, optionally, for MG users we should write a web frontend for this around the time we start working on an installer

**Comment by curtisdelicata** [comment]
Yes this would be useful for a installer. We would also have to write the config files (There is a Kohana way of writing to config files??)

**Comment by happyDemon** [comment]
I think we could slightly modify @hinton 's langify module to do this, l18n files are stored in the same format as config files if I remember correctly.

**Comment by curtisdelicata** [comment]
Ok sounds good

**Comment by happyDemon** [comment]
I was wondering if we'll be supporting localization at any point?

**Comment by Hinton** [comment]
We should yes there are a few different approaches on how we should deal with it, but I don't think we should squeeze it in for 1.0

**Comment by curtisdelicata** [comment]
I don't think we should worry about localization until after 1.0

**Comment by Hinton** [comment]
I was thinking that we should go over our current database design, add more indexes and optimize the length.

The user table is currently quite bloated, we should try to move our stuff we no longer need from it.
For example there should be no need to have avatar, gravatar, avatar_id. And what purpose does users_avatars serve? I fail to see how a user can have many avatars, but maybe I'm missing something?

**Comment by curtisdelicata** [comment]
users_avatars is because the table is a list of avatars they have unlocked I thought? and avatar_id links to their current avatar?

**Comment by happyDemon** [comment]
yup curtis is right. avatar_id is for the user's current active avatar, while users_avatars holds unlocked avatars the users can use.

**Comment by happyDemon** [comment]
You're right by the way, we should add correct Keys so we can make use of  CASCADE on DELETE. This would help the ORM delete any records related to the key. for example when a user's deleted we'd want to delete all data linked to the users (user_tokens, user_items, user_avatars) since the data would otherwise be a useless waste of DB space.

**Comment by Hinton** [comment]
Yea, I'm working on that. I added them for users_avatars but user_titles still misses it.

**Comment by curtisdelicata** [comment]
Can this be closed now as migrations have all been written?

**Comment by happyDemon** [comment]
hold on, after some testing I seem to be getting an erro in the trades migrations

**Comment by happyDemon** [comment]
oki trade migrations are all fixed up, we can finaly make use of migrations :D
