### ISSUE TITLE
Abstract class placement

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#83]
I propose that we place abstract classes inside a folder Abstract.

For example should `Controller_Frontend` be called `Controller_Abstract_Frontend`.
This should give a clearer view of what controllers are abstract and prevent a visitor from accidentally visit it (would trigger an error).

Would this be a good idea, or should we stick with how we currently handle it, or any other naming suggestions?

**Comment by happyDemon** [comment]
Seems like a good practice to store base, AKA Abbstract controllers in their respective folders, not to cloud the Controller folders with controllers that won't be actively routed to.

**Comment by Hinton** [comment]
We should also use the same principle for View classes, as they also clutter up the directory.

**Comment by curtisdelicata** [comment]
Sounds like a good idea. Do other Kohana applications do similar?

**Comment by Hinton** [comment]
https://github.com/synapsestudios/kohana-projecttemplate/ uses /Abstract/Controller/ format, it might be better than /Controller/Abstract.
Vendo, https://github.com/vendo/core/blob/develop/classes/controller.php extends the controller class.

Would it be better to use /Abstract/Controller and /Abstract/View than /Controller/Abstract ?

**Comment by curtisdelicata** [comment]
Thanks. We should follow how project template does it.
