### ISSUE TITLE
Rename User in Views

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#84]
The current logged in user is currently accessed using the function User in View_Base.
This causes a few confusions while trying to set another user, therefore it might be good to rename it to current_user or something similar.

**Comment by happyDemon** [comment]
We could rename it to player? Easy to remember, no underscore needed :D

**Comment by Hinton** [comment]
Player makes sense.

So player would refer to the currently logged in user while user refers to whatever "user we have to deal with".

**Comment by happyDemon** [comment]
yupyup

**Comment by curtisdelicata** [comment]
I was going to say to use current_user but player seems ok.
