### ISSUE TITLE
Fix Debug-Toolbar or PHP Quick Profiler?

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#85]
The current debug toolbar works fine, however it needs some work.
We should disable the automatic rendering as it breaks json.

There are a few alternatives to Debug-Toolbar.
https://github.com/Alert/profilertoolbar seems more or less the same but provides some more features.

http://www.particletree.com/features/php-quick-profiler/ looks awesome but we would have to port it, I don't think it would be that much work as we should be able to use the data from Profiler class (Kohana). A more up-to-date version seems to exist in fuelphp codebase, https://github.com/fuel/core/tree/1.5/develop/vendor/phpquickprofiler.

**Comment by happyDemon** [comment]
I quite like https://github.com/Alert/profilertoolbar 's look less cluttered than pqp's and seems to have more features targetted at Kohana.

It also seems to be actively maintained (last repo update was from 3 months ago) whilst pqp is dated from 2009

**Comment by Hinton** [comment]
I gave PQP a try and it takes up nearly the whole browser window while active, making it quite bothersome to use sadly.

**Comment by Hinton** [comment]
Forked profilertoolbar to modulargaming and created the 3.3 branch.

**Comment by curtisdelicata** [comment]
I agree that profiletoolbar seems the best option.

**Comment by Hinton** [comment]
I modified debug-toolbar so it won't autorender anymore, and I improved the route tab slightly with a few features from profilertoolbar.
