### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#86]
We need to minify assets in production.

**Comment by curtisdelicata** [comment]
Can this now be closed?

Does asset-merger handle this?

**Comment by happyDemon** [comment]
yup, but I'm stll working on it, it's not stable at the moment

**Comment by happyDemon** [comment]
The new asset branch should now work correctly with the asset-merger module

**Comment by happyDemon** [comment]
this means that in asset config files you can now specify fallback files and conditionals in the option property.

As an example for CSS files you could add an internet explorer conditional like so:

``` php
return array (
    'global' => array(
        'head' => array(
            'css' => array(
                array(
                    'name' => 'bootstrap',
                    'file' => 'bootstrap.css',
                    'options' => array('condition' => 'gte IE 7'),
                ),  
            )
        )
    )
);
```

https://github.com/OpenBuildings/asset-merger#ie-conditional-comments

The options property in JS files could contain a local fallback when loading remote files
https://github.com/OpenBuildings/asset-merger#js-local-fallback

**Comment by happyDemon** [comment]
_copy from hall_

with this latest push to the asset branch I've run into some trouble
the main site renders all the assets
but in the admin they won't show up
if I do a var_dump I see that they are being generated though
if I do an echo they do get printed
they just don't get show up in the template o.O
anyone who can help? xD

**Comment by happyDemon** [comment]
just pushed an update to WIP-assets branch, needs the asset-merger module to be updated though (there's a bug in the older version).
Not a lot of the syntax was changed, so updating our current codebase was easy.

I've got this working on my local instalation (I hope I pushed everything though).

Oscar mentioned something about loading all on-site assets at once so they all get merged into 1 file in production, that's something that still needs to be implemented (I think it's best to do this near the release, correct me if I'm wrong).

**Comment by Hinton** [comment]
Well, we don't exactly have a need for it at the moment, but it should be fairly simple changes so it might be worth looking into it now rather than putting it off.

**Comment by curtisdelicata** [comment]
Can this be closed now?

**Comment by Hinton** [comment]
No, it's not working at all.

**Comment by Hinton** [comment]
Our current problem is that not all pages use the same assets, a few pages include special js files.
We have to start with including all the "frontend" javascript files on all pages.

**Comment by happyDemon** [comment]
We could make a minion task that reads out the global asset files from the config file and merges them?
having one extra js file on a page load here and there wouldn't hurt, would it?

if you agree I'll start on the task tomorow ^^

**Comment by Hinton** [comment]
Well, it won't exactly hurt, but it will be an additional http get and it means you got no way to use a CDN easily.

**Comment by happyDemon** [comment]
you're right there, we could combine them all together if that wouldn't bloat the one file too much (which is something I'd worry about in the admin)

**Comment by curtisdelicata** [comment]
When I updated a Javascript file it did not update the cached version in assets, I had to delete it and load again.

**Comment by curtisdelicata** [comment]
It currently fails when environment is set to production

**Comment by curtisdelicata** [comment]
ErrorException [ Fatal Error ]: Call to undefined method Asset_Merger::html()

MODPATH/asset-merger/classes/Kohana/Asset/Collection.php [ 124 ]

**Comment by curtisdelicata** [comment]
Replacing with the function call from Asset_Merger::html to Asset::html fixes this. I need some advice if this is the correct way before I push.

@hinton @happyDemon @modulargaming

**Comment by Hinton** [comment]
I was thinking of rewriting the assets system into a more lightweight solution, it's a bit bloated and to complicated for our needs currently.

@curtisdelicata if it works push it, it can't be worse than the current error.

**Comment by curtisdelicata** [comment]
I think it is good. I don't think we need a rewrite. It is up to you though.

What do you think? @happyDemon @Lewis @jannesiera @modulargaming 

I will change and push.

**Comment by curtisdelicata** [comment]
Asset Merging now appears to work?

It successfully creates head.css and everything is merged into it.

**Comment by curtisdelicata** [comment]
Javascript seems to be broken.

When in production I cannot change specie or colour on pet create.

**Comment by Lewis** [comment]
Pet create is fixed. The JavaScript wasn't in the assets.php.

**Comment by Lewis** [comment]
I copied how Abstract_Controller_Frontend loads assets to HTTP_Exception. Was that the correct way?

**Comment by curtisdelicata** [comment]
It looks correct. Thanks.

What do you think @hinton

**Comment by Hinton** [comment]
I was considering using HMVC to call a controller that renders the error pages. Not sure what the best practice is.

**Comment by curtisdelicata** [comment]
Lewis mentioned that he found that if he changed it to use admin-head.css and admin-body.js that it worked. That is because the assets get generated for the user side and cannot be updated again for admin as the file has already been loaded. Would this be a good idea? It would be an if statement and new files.

Quoted by @happyDemon 

with this latest push to the asset branch I've run into some trouble
the main site renders all the assets
but in the admin they won't show up
if I do a var_dump I see that they are being generated though
if I do an echo they do get printed
they just don't get show up in the template o.O
anyone who can help? xD

**Comment by Lewis** [comment]
I have made the admin pages load assets with "_admin" added to the end of the file name but the pages with data tables try load separate JavaScript files which don't get loaded because body_admin.js has been cached from the previous page.

**Comment by curtisdelicata** [comment]
@hinton said he is going to rewrite assets when he has time. Do not worry about fixing the current implementation @Lewis proceed with messages/games.
