### ISSUE TITLE
Upgrade jQuery to 1.9 

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#87]
jQuery 1.9 was released today, we should upgrade to it.

We should also consider using 2.0 as standard and provide fallback to 1.9 for ie 6,7,8.

``` html
<!--[if lt IE 9]>  
    <script src="jquery-1.9.0.js"></script>  
<![endif]-->  
<!--[if gte IE 9]><!-->  
    <script src="jquery-2.0.0.js"></script>  
<!--<![endif]-->
```

!!! upgraded to 1.9, 2.0 is still beta, we'll come back on this at a later time

**Comment by happyDemon** [comment]
using 2.0 is still to early since it's in beta, have you checked if anything from the bootstrap library breaks?
we shouldn't be using the migrate plugin they offer if we're actually upgrading, if we would we could just as wel stay on the current version.

**Comment by curtisdelicata** [comment]
1.9 will be fine for now. We should wait before we use 2.0 as it is still beta.

**Comment by happyDemon** [comment]
we'd also need to tweak the asset collector to incorporate these conditional blocks

**Comment by happyDemon** [comment]
I updated any javascript I already made to accompany the move to 1.9
