### ISSUE TITLE
Rss feed at dashboard

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#88]
We should have an rss feed widget at the admin panel dashboard that displays the latest news for MG.

**Comment by happyDemon** [comment]
This is a great idea

**Comment by curtisdelicata** [comment]
I agree that this is a good idea. ModularGaming.com does not use a content management system but I can create a RSS feed manually.

**Comment by curtisdelicata** [comment]
http://www.modulargaming.com/rss.xml

**Comment by curtisdelicata** [comment]
I tried following:http://kerkness.ca/kowiki/doku.php?id=working_with_atom_and_rss_feeds#parsing_a_remote_feed

but I am having issues with it.

**Comment by happyDemon** [comment]
Could you describe what problem you're having?

**Comment by curtisdelicata** [comment]
It won't let me access the information as an object or as an array.

**Comment by happyDemon** [comment]
I can't help you without any code xD
if you're stuck you could always try to browse Kohana's guide (or browse through the api that's generated in the userguide module)

**Comment by curtisdelicata** [comment]
Controller:

```
            $feed = Feed::parse('http://www.modulargaming.com/rss.xml');
            $this->view = new View_Admin_Dashboard_Index;
            $this->view->feed = $feed;
```

View:

```
    public function feed()
    {
            $feed = $this->feed;

            return array(
                    'title'      => $feed->title,
            );
    }
```

Template:

{{^feed}}
No feed.
{{/feed}}

{{#feed}}
{{title}}
{{/feed}}

Error:

 Trying to get property of non-object

**Comment by curtisdelicata** [comment]
View:

```
    public function feed()
    {
            $feed = $this->feed;
    }
```

Outputs 'No feed'

**Comment by happyDemon** [comment]
http://kohanaframework.org/3.3/guide-api/Feed#parse

there you can see how your feed is being parsed.
If you're still having troubles I'll be able to have a look tomorow ^^

**Comment by curtisdelicata** [comment]
Got it working. I forgot to return $feed.
