### ISSUE TITLE
Follow Kohana's Conventions and Style

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#89]
We SHOULD follow [Kohanas Conventions and Styles](http://kohanaframework.org/3.3/guide/kohana/conventions), if we disagree about something we MUST write our own guideline and follow it!

Most of our code follows the convention, there are a few new additions, mostly by @happyDemon that do not follow it.

I'm not saying we have to follow it, 100% but we have to decide on a set of rules that we will follow, preferable they should be based upon Kohanas Convention.

**Comment by happyDemon** [comment]
I'm guessing you're talking about the way I do my conditions?
I'll change them, if there's anything else, let me know

**Comment by curtisdelicata** [comment]
I agree with this proposal. Let me know if there is anything I am doing wrong.

**Comment by curtisdelicata** [comment]
Can this now be closed?
