### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#91]
I was wondering if it's still too late to switch around the pagination module.

https://github.com/morgan/kohana-paginate
http://dev.morgan.ly/kohana/v3.3/guide/paginate/

I personally think it simplifies the way we would handle pagination on pages, it doesn't offer an implementation, writing our own for kostache wouldn't be a problem.

next to standardising page-pagination, it also offer a standard way of paginating searches.

**Comment by curtisdelicata** [comment]
The benefit of using Kohana Pagination is that it is an 'official' module. However this looks interesting. We should wait and see what Oscar says about it.

**Comment by happyDemon** [comment]
it used to be an official one, I think it was around 3.0, but it hasn't been included in official releases, making it an unofficial module.
If you poke around in there forums the core devs said that there are better ways to handle pagination than the implementation they had previously included in official release.

Who's mainting the pagination module by the way? I bet it's not a core dev :P

**Comment by curtisdelicata** [comment]
I did not know that it is not official. It should of been obvious as there is no 3.3 for it, I had to clone a fork of a fork and then update it.

I have looked at the guide for this one and it looks better.

**Comment by Hinton** [comment]
Shadowhand seems to be maintaining it, not sure why we use a fork of a fork of a fork over at mg/pagination.
https://github.com/shadowhand/pagination/tree/3.3/master

**Comment by happyDemon** [comment]
@hinton was possitive about it too, but said he didn't want to give a specific answer until he was better. I guess we'll have to wait a bit longer if we're going to do the switch.

strange that shadowhand would be the one maintaining it xD lol forkception o.O

**Comment by happyDemon** [comment]
Ugh, thank you coffee rush, didn't notice your reply was yours Hinton xD
So we'll incorporate this?

**Comment by curtisdelicata** [comment]
I originally forked from one that had extra changes on how the request works. I did not see a 3.3 branch on the main one. I have now forked the main pagination and tested it and it works.

Feel free to change it though, as the one you mentioned looks interesting.

**Comment by Hinton** [comment]
I took a look at the pagination module, it seems like a better solution than our current module, however!

It does not support configuration file(s), what I liked about the current is that you can specify a standard global limit that will be used unless you specify one in the pagination builder (Keeps it consistent over the whole site).
It also has no render function, so we have to write one that takes advantages of routes, as it only exposes count and total_count.

**Comment by curtisdelicata** [comment]
I think the one we currently have is good enough however I am happy whichever one is used. Feel free to change.

**Comment by curtisdelicata** [comment]
Have we decided now? I am happy with either one.

@hinton @happyDemon @Lewis

**Comment by happyDemon** [comment]
I'll try to get an implementation ready with a global config today ^^

**Comment by curtisdelicata** [comment]
I had an error on trying to install new module using existing installation. I tried with a fresh clone and it failed at pagination.

I deleted the module and re added. I also renamed it to paginate.

**Comment by curtisdelicata** [comment]
The first error said does not point to a valid commit. On fresh clone I got an error about branch. I've tested it and I've got it working fine now.

**Comment by curtisdelicata** [comment]
Can this be closed now? Or should we close it after we implement pagination in existing modules?

**Comment by happyDemon** [comment]
I think we'd better wait until all the existing modules get updated with the new pagination class^^

**Comment by Hinton** [comment]
I am currently cleaning up the paginate class a bit, and I have an idea for improvement.

We should only support an array as config, and we should merge the default config file with the config array.

Our new api would be, `factory($object, array $config = array(), $driver = NULL)`

**Comment by happyDemon** [comment]
Are you sure you'd need to offer $driver? MG is only concerned with the default ORM, no? otherwise it's all good :D

**Comment by Hinton** [comment]
True, removed the driver and added Request. 56f7fc2cdb67f158093cece53f943a6aa23557ed

**Comment by Lewis** [comment]
I get an error when I view something using pagination when there are over 20 items "ErrorException [ Notice ]: Undefined variable: suffix"

http://demo.modulargaming.com/forum/topic/1
