### ISSUE TITLE
User profile - pets

### ISSUE THREAD

**Issue by curtisdelicata** [modulargaming/modulargaming#94]
The user profile has a list of the users pets. This should be done using an event.

**Comment by curtisdelicata** [comment]
I am a bit confused how this would work? Can we mention a function in the init.php and the code/function is in a separate file? As we don't want to put the whole thing in init.php

@Lewis @happyDemon

**Comment by happyDemon** [comment]
it uses this function: http://php.net/manual/en/function.call-user-func-array.php

so you could do something like

``` php
$object = new some_class;
Event::listen('event.name', array($object, 'method_you_want_to_call_on_it');
//or just call a static method
Event::listen('event.name', array('some_class::method _you_want_to_call_on_it');
```
