### ISSUE TITLE
Toying with CSRF

### ISSUE THREAD

**Issue by happyDemon** [modulargaming/modulargaming#96]
This is being a pain in the ass for me whenever I create and POST ajax request, so I was wondering if we could switch things a little up without losing it's functionality, or even beter, its purpose.

At this point a token gets generated on a page load, put in a sessions and if the form is submitted the controller checks if the token is the same as the csrf field in the form.

I think it might be nice for ajax requests to only check where the requests is coming from (e.g. by the request's referer and/or origin), which would make it as secure as csrf, otherwise we'd have to generate a new token everytime we're about to POST data through (e.g. send an extra request before submitting the data).

would this be ok to implement? or are there other options to this?

**Comment by curtisdelicata** [comment]
I would prefer that we keep CSRF for forms submitted. Checking just for the requests referrer and/or origin for AJAX requests should be fine, the referrer or origin can be modified though?

What do you think about this @hinton

**Comment by happyDemon** [comment]
Yes, that's true, they can be modified and yup, this would only count for the ajax requests.

I'm just not sure how we'd generate a token for ajax requests. If we minify the js files we can somewhat hide the url (i think), which would help slightly, but other than that I'm clueless.

**Comment by Hinton** [comment]
CSRF Tokens are currently generated once and re-used meaning the CSRF token won't change during a players visit, and we could use the same token for all ajax requests.

Checking origin should protect against most attacks but we should also send along the CSRF token.

**Comment by happyDemon** [comment]
ok, so it's just a matter of sending through the csrf token with all the POST requests? allriight :D I'll try to incorporate it in all my requests by tonight

**Comment by happyDemon** [comment]
in the meantime I hacked something together in the frontend controller, will be gone by the time I'm sending csrf tokens along with the requests

**Comment by curtisdelicata** [comment]
Are we still going to be sending through the CSRF token with all POST requests?

**Comment by happyDemon** [comment]
yupyup, this is going to be part of the clean up today, all post ajax requests will be sending the csrf token.

**Comment by curtisdelicata** [comment]
Ok thanks

**Comment by Lewis** [comment]
Ok

**Comment by curtisdelicata** [comment]
Can this now be closed?

**Comment by happyDemon** [comment]
yup, should be complete now
