### ISSUE TITLE
Last_Post user select query (Category view).

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#97]
The forum topic list does additional unwanted sql selects for the last_post user object.

I haven't been able to get it to join the last_post.user object, not even sure if it's possible as it's nested. It's also creating a quite complicated query.

Do we need to show what user last replied to the thread, and if we do how do we best solve it, doing a select for each topic is unacceptable.

**Comment by curtisdelicata** [comment]
I think we should show the last replied. Unsure on best way to implement though.

**Comment by curtisdelicata** [comment]
I'm sure that I saw on hall that you found out a way to do a join?

**Comment by Hinton** [comment]
Ah yes, this should be closed.
