### ISSUE TITLE
Move breadcrumb to View classes

### ISSUE THREAD

**Issue by Hinton** [modulargaming/modulargaming#98]
I have been unhappy with the breadcrumb solution for a while, I designed it as a static class, being more or less a simple array with add and get being its only functionality.

I believe it would be more "correct" to have the breadcrumb logic inside the view classes. We could still retain most functionality such as adding breadcrumb in the before function by better extending classes for views.

We should try to prevent having a static class if possible and rather have a function that returns the breadcrumb array directly in the view class.

Any suggestions?, @curtisdelicata, @happyDemon, @Lewis.

**Comment by happyDemon** [comment]
I'm guessing this is what you're looking for: http://laravel.com/docs/ioc ?
The actual code is here: https://github.com/laravel/laravel/blob/master/laravel/ioc.php

It's uses the event library which we already have ^^

Edit: there's a workaround that wouldn't require this I just noticed xD nevermind ^^

**Comment by curtisdelicata** [comment]
Using views instead of controller sounds the best way.

**Comment by Hinton** [comment]
@happyDemon My goal was to remove the breadcrumb class and move the breadcrumb data to the view classes.

``` php
public function breadcrumb()
{
    return array( <BREADCRUMB> );
}
```

**Comment by Hinton** [comment]
I created a new branch with a new breadcrumb design. @curtisdelicata, @happyDemon, @Lewis could you all take a look and decide if it's an improvement over the old?

**Comment by curtisdelicata** [comment]
It doesn't look as nice as the breadcrumb function currently. I guess if it is the proper way to have it in the View then feel free to proceed.

**Comment by happyDemon** [comment]
I'm going to have a look at this the second I get home ^^

**Comment by curtisdelicata** [comment]
Could we call it using a similar method to how we called it in the Controller? As it looked cleaner with Breadcrumb::add

**Comment by Hinton** [comment]
The other alternative would be to have a function inside the view, `add_breadcrumb($title, $url)`, and place the call inside the constructor.

``` php
public function __construct()
{
    $this->add_breadcrumb(
        'Home',
        '/'
    );
}
```

**Comment by Hinton** [comment]
Hmm, on a second thought, that won't work, considering we need to set properties before calling the breadcrumb.
